Xilinx/RapidWright

com/xilinx/rapidwright/util/Installer.java
Unless I'm mistaken, you should be comparing all parameter strings to `arg` (a String), not `args` (a String Array).
=> Compare parameter string to arg instead of args

src/com/xilinx/rapidwright/design/ModuleInst.java
When we were trying to connect: 
1) one bit of a multi-bit port to another single-bit port, or 
2) one bit of a multi-bit port to another bit of another multi-bit port (different indices), 
it seems that there was a restriction on the method `connect(...)`. 
Therefore, I improved the method `connect(...)` to allow a more flexible connecting, which also allowed the previously mentioned connecting to be possible.
=> Update ModuleInst.java for a more flexible connecting

src/com/xilinx/rapidwright/timing/DelayModel.java, src/com/xilinx/rapidwright/timing/SmallDelayModel.java, src/com/xilinx/rapidwright/timing/TimingGraph.java, src/com/xilinx/rapidwright/timing/TimingModel.java
Makes the DelayModel public and modifies one of the interface APIs to more precisely take a SiteTypeEnum rather than a String.
=> Delay model changes

src/com/xilinx/rapidwright/design/blocks/PBlockGenerator.java, tcl/rapidwright.tcl
Added the following features: 
- algorithm for higher horizontal density = pblocks will try to use different columns
- algorithm for computing more compact pblocks (for exp. clbs closer to brams in case bigger patterns are chosen)
- new algorithm selects the slice from a tile depending on whether it is a _R or _L clb
- new algorithm selects the pblock width having in mind also 7. series devices which have 2 slices/tile
=> Horizontal density

src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
@clavin-xlnx Can you run this through your test set, and see if it explodes.  I've done some initial tests and it seems to be catch the problem I wanted to detect.
=> Add constant net check.

interchange/DeviceResources.capnp, src/com/xilinx/rapidwright/interchange/DeviceResources.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
Minimal pseudo PIP blockage map data.
=> Draft changes for pseudo PIP blockage data.

interchange/DeviceResources.capnp, src/com/xilinx/rapidwright/interchange/DeviceResources.java
I'm working on adding logic to `DeviceResourceWriter` / `DeviceResourceVerifier` to populate this.
=> Add Cell BEL pin mapping schema.

src/com/xilinx/rapidwright/interchange/CellBelMapping.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java, src/com/xilinx/rapidwright/interchange/EnumerateCellBelMapping.java
This also provides a workaround for #101
=> Fix Cell BEL pin mapping now that initial bugs are fixed.

interchange/DeviceResources.capnp, src/com/xilinx/rapidwright/interchange/DeviceResources.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java, src/com/xilinx/rapidwright/interchange/LogNetlistReader.java
This adds a schema description for local site inverters, how to control them, and how to route them.  This is a peer to the inverting property on `SitePips` in the `PhysicalNetlist`.
=> Add schema for describing local site inverters.

src/com/xilinx/rapidwright/interchange/ConstantDefinitions.java, src/com/xilinx/rapidwright/interchange/DeviceResources.java
This covers what cell is used in the LogicalNetlist for constant
sources, and the name of the constant nets in the PhysicalNetlist.
This PR depends on schema changes specified in https://github.com/SymbiFlow/fpga-interchange-schema/pull/9 .  https://github.com/SymbiFlow/fpga-interchange-schema/pull/9 should be reviewed/merged before this one.
=> Add missing constant data to DeviceResources.

interchange/README.md
Signed-off-by: Reilly McKendrick <romckend@byu.edu>
=> Altered update instructions to match main README

src/com/xilinx/rapidwright/tests/PinMapTester.java
This is a little tool to explore where the problems seen in #143 are coming from.
=> Add PinMapTester tool to check P2L mapping from RapidWright.

src/com/xilinx/rapidwright/edif/EDIFParser.java
RapidWright can *almost* parse EDIF files written by Yosys, as they both aim to be compatible with Vivado. This PR aims to make it fully compatible:
* Make the `status` header optional.
* Support `external` libraries (handled like regular libraries).
* Support Cell Instances not specifying a library for the cell they refer to. They default to the current library.
=> make EDIF parsing more flexible

src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
To accommodate changes related to https://github.com/SymbiFlow/fpga-interchange-schema/issues/17 and https://github.com/SymbiFlow/fpga-interchange-schema/pull/21.
=> Removing tile pattern idx for now.

src/com/xilinx/rapidwright/gui/ModuleInstanceScene.java, src/com/xilinx/rapidwright/gui/UiTools.java, src/com/xilinx/rapidwright/placer/handplacer/HandPlacer.java
* Add View for single module instance and all its placements
* Extract Saving to PDF to new class
* Add Saving to SVG
=> UI improvements

src/com/xilinx/rapidwright/gui/TileScene.java
In `TileScene`, the FPGA fabric is cached in a pixel image once and then repeatedly drawn. While this is advantageous when repeatedly drawing a GUI, it is not great when exporting vector images. Files are bigger, slower to load and no longer infinitely scalable.
This PR makes using the image optional. It should still be used for GUIs, but not for Vector exports.
=> add switch to not use Pixel Images in visualizations

src/com/xilinx/rapidwright/interchange/DeviceResources.java, src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java, src/com/xilinx/rapidwright/interchange/WireType.java
See SymbiFlow/fpga-interchange-schema#31
=> interchange: Add wire types to DeviceResources

src/com/xilinx/rapidwright/util/JobQueue.java
=> fix detection of LSF Availability

src/com/xilinx/rapidwright/util/JobQueue.java, src/com/xilinx/rapidwright/util/LSFJob.java
There is a Race Condition between starting LSF jobs and our first query to see if the job is still running. The current delay of 8 seconds is enough in most cases, but not always (at least for me). Instead of just increasing the delay, this PR fixes the Race Condition.
We now query LSF for the job status. This allows us to reliably differentiate between not yet started and finished jobs.
=> Fix Race Condition - Query LSF for job status

src/com/xilinx/rapidwright/device/browser/DeviceBrowser.java, src/com/xilinx/rapidwright/gui/TileView.java, src/com/xilinx/rapidwright/gui/WidgetMaker.java
Various small Improvements to the Device Browser
* Keep centered on Mouse cursor when Zooming in GUI
* allow setting part by command line argument
* sort devices in list
=> Device browser improvements

.github/workflows/build.yml, build.gradle, test/com/xilinx/rapidwright/design/TestRelocation.java, test/com/xilinx/rapidwright/device/TestPartNameTools.java
Also includes some testcases for some of my recent work
=> Add JUnit 5 & Test on Github Actions

.github/workflows/build.yml, .github/workflows/upload-test-results.yml
Hopefully I got it right this time, sorry for all the PR spam.
=> support uploading test results in PRs

.github/workflows/build.yml
This should fix the build failure on master
=> do not try to restore the Github Cache from old release

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFNetlist.java
I introduced more issues in #207. Fixing them here...
=> Edif hierarchy fixes

src/com/xilinx/rapidwright/device/helper/TileColumnPattern.java, src/com/xilinx/rapidwright/examples/TileWindow.java, src/com/xilinx/rapidwright/gui/TileColors.java, src/com/xilinx/rapidwright/gui/TileScene.java, src/com/xilinx/rapidwright/util/Utils.java
Various Improvements around supporting URAMs:
* Like other tile types, list them in Utils.java
* Show them in TileScene
* Search for them in TileColumnPattern. Additionally search for or avoid Laguna Tiles
This also adds two missing switchbox tile types to Utils.isSwitchBox: INT_INTF_L and INT_INTF_R
=> URAM Support in UI and TileColumnPattern

src/com/xilinx/rapidwright/util/DataVersions.java
=> Adds CFGLUT5 and BUFG to macros.

Makefile
=> Removes data zip download with download on-demand now implemented

test/com/xilinx/rapidwright/design/TestDesign.java
Demonstrates bug where `ModuleInst` anchors not being read from DCPs correctly.
=> Add DCP ModuleInst anchor test

src/com/xilinx/rapidwright/edif/EDIFNetlist.java
=> Guard against null internal nets. Fix for #248

src/com/xilinx/rapidwright/design/DesignTools.java, test/com/xilinx/rapidwright/design/TestDesignTools.java, test/com/xilinx/rapidwright/design/TestSiteRoutingResolver.java
=> Site routing resolver when combining in-context module designs.

src/com/xilinx/rapidwright/design/tools/RelocationTools.java, src/com/xilinx/rapidwright/util/Utils.java
Result of this discussion https://github.com/Xilinx/RapidWright/discussions/292#discussioncomment-1661671 as discovered by @bn999.
=> RelocationTools to relocate more Site types

src/com/xilinx/rapidwright/edif/EDIFNetlist.java, test/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
=> Restructure macro/prim expansion exceptions

src/com/xilinx/rapidwright/design/PBlockCorner.java, src/com/xilinx/rapidwright/design/blocks/PBlockRange.java
=> Refactoring confusing CLOCK_REGION string

src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java, src/com/xilinx/rapidwright/interchange/EnumerateCellBelMapping.java, test/com/xilinx/rapidwright/interchange/TestCellBELMappings.java, test/com/xilinx/rapidwright/interchange/TestDeviceResources.java
=> Fix for #326

src/com/xilinx/rapidwright/router/Router.java
=> Don't allow router to swap pins that aren't LUT inputs

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/util/FileTools.java
=> Better handling of null parent nets

src/com/xilinx/rapidwright/MainEntrypoint.java, src/com/xilinx/rapidwright/interchange/GenerateInterchangeDevices.java
=> Easy command to generate all interchange device files

src/com/xilinx/rapidwright/util/FileTools.java
=> Pre-requisite changes to enable uncommon node cache

src/com/xilinx/rapidwright/util/ParallelismTools.java
=> Enabling parallelism (for write DCP) by default

test/com/xilinx/rapidwright/design/TestDesign.java
=> Add test for #349 (needs Vivado, skipped on GH's CI)

.github/workflows/check-git-submodules.yml, Makefile
=> Redirect 'make update_jars' at 'gradlew update_jars'

.classpath, .github/workflows/build.yml, RELEASE_NOTES.TXT, test/com/xilinx/rapidwright/support/CheckOpenFilesExtension.java
=> Begin 2021.2.2 release testing

src/com/xilinx/rapidwright/timing/TimingModel.java
This fixes a deprecation warning that pops up in every build
=> Replace deprecated float constructor with Float.valueOf

src/com/xilinx/rapidwright/design/tools/LUTTools.java
=> Adding LUT utility API to get BELs from character

src/com/xilinx/rapidwright/util/Utils.java
=> Augmenting IOB types.

.github/workflows/build.yml, src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFNetlist.java, src/com/xilinx/rapidwright/edif/EDIFTools.java, test/com/xilinx/rapidwright/edif/TestEDIFTools.java
=> Method to create a new netlist using existing EDIFCellInst as top cell

src/com/xilinx/rapidwright/edif/EDIFTools.java
=> Enables parallel EDIF parsing by default

src/com/xilinx/rapidwright/util/RapidWright.java
=> Fix executable jar unpack message

.classpath, .github/workflows/build.yml, RELEASE_NOTES.TXT, test/src/com/xilinx/rapidwright/design/TestDCPLoad.java
=> 2022.1.1 Staging Branch

src/com/xilinx/rapidwright/device/browser/DeviceBrowser.java, src/com/xilinx/rapidwright/gui/WidgetMaker.java
Prior to this change, without downloading devices, the `DeviceBrowser` would be not functional.
=> Allows DeviceBrowser to browse devices prior to downloading them.

src/com/xilinx/rapidwright/edif/EDIFTools.java, test/src/com/xilinx/rapidwright/edif/TestEDIFTools.java
```
* @return True if uniqueification necessary and performed, False if not necessary. Null if indeterminable.
```
=> EDIFTools.uniqueifyNetlist() to return Boolean

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
=> Changes to correlate with a site wire memory optimization

src/com/xilinx/rapidwright/edif/EDIFNetlist.java
=> Fix initialization for Gnd pins

src/com/xilinx/rapidwright/design/noc/ComponentType.java
=> Add missing NOC ComponentTypes

gradle/wrapper/gradle-wrapper.properties
Signed-off-by: gatecat <gatecat@ds0.me>
=> Bump gradle version for Java 18 support

test/src/com/xilinx/rapidwright/design/TestDesign.java, test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
Adds test, increases memory requirements for longer running RWRoute tests that are failing sporadically.
=> Adds a test for copy cell fix

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFCell.java
These lines are not needed based on the subsequent lines behavior.
=> Fixes issues with PopulateBlackBox()

src/com/xilinx/rapidwright/design/DesignTools.java, test/src/com/xilinx/rapidwright/design/TestDesignTools.java
=> Fixes issues around makeBlackBox(), batches pin removals

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/design/tools/LUTTools.java, test/src/com/xilinx/rapidwright/design/tools/TestLUTTools.java
=> Convenience method to get a companion LUT from an existing one

.classpath, .github/workflows/build.yml, src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/design/tools/RelocationTools.java, src/com/xilinx/rapidwright/edif/EDIFTools.java, test/src/com/xilinx/rapidwright/design/merge/TestMergeDesigns.java
=> 2022.1.2 RC5 Jar

src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java, src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java, test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
Also partially revert #253 by allowing routethru cells to be expressed again.
=> Refactor PhysNetlistWriter

src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
Provides more useful checking message on Interchange design import.
=> Adds warning message when pin mappings don't match

src/com/xilinx/rapidwright/util/PlacerDirective.java, src/com/xilinx/rapidwright/util/RouterDirective.java
=> Adds new placement and router directives in Vivado

src/com/xilinx/rapidwright/design/DesignTools.java
=> Fix to populateBlackBox, avoids concurrent mod

src/com/xilinx/rapidwright/examples/SLRCrosserGenerator.java
fixes https://github.com/Xilinx/RapidWright/issues/520
=> Fix `SLRCrosserGenerator`

python/setup.py, python/src/rapidwright/rapidwright.py, src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFNet.java, src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java, src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java, test/src/com/xilinx/rapidwright/design/TestDesignTools.java, test/src/com/xilinx/rapidwright/edif/TestEDIFNet.java, test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
=> Add a JUnit test runner that runs all tests on LSF 

src/com/xilinx/rapidwright/edif/EDIFNetlist.java, test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
=> Fix Macro Expansion

test/src/com/xilinx/rapidwright/design/TestSiteInst.java
Tests fixes for F8MUX site routing in UltraScale slices.
=> Test for F8MUX site routing

src/com/xilinx/rapidwright/examples/RunSATRouterExample.java, src/com/xilinx/rapidwright/router/SATRouter.java
- Allows the random SEED to be set from the command line
- Allows for return code 1 in evRouter (still generated valid solution in this case)
=> Fix SAT Router Example

test/src/com/xilinx/rapidwright/device/TestBEL.java
For the handful of pins handled by `RouterHelper.invertPossibleGndPinsToVccPins()`
=> Test BEL.canInvert()

src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java, test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistReader.java
=> [Interchange] Create LUT routethru cells if not present

src/com/xilinx/rapidwright/router/RouteThruHelper.java, src/com/xilinx/rapidwright/util/FileTools.java
=> Move routethru helper cache to data directory

src/com/xilinx/rapidwright/design/DesignTools.java, test/src/com/xilinx/rapidwright/design/TestDesignTools.java
... to not connect A6 to VCC unless there is a corresponding [A-H]5LUT cell placed.
=> Fix DesignTools.createMissingStaticSitePins() when only LUT6

test/src/com/xilinx/rapidwright/design/TestCell.java
=> Test for the fix of Cell.getCorrespondingSitePinName() 

test/src/com/xilinx/rapidwright/device/TestNode.java
Signed-off-by: Eddie Hung <eddie.hung@amd.com>
=> Test that Node.getAll{Uphill,Dowhill}Nodes() are unique

test/src/com/xilinx/rapidwright/design/TestDCPWrite.java
=> Test for #572

src/com/xilinx/rapidwright/edif/EDIFPortInstList.java, test/src/com/xilinx/rapidwright/edif/TestEDIFPortInstList.java
=> Change EDIFPortInstList duplicate behavior to overwrite

src/com/xilinx/rapidwright/tests/CodePerfTracker.java
=> Option to report OS memory usage without enabling useGCToTrackMemory

src/com/xilinx/rapidwright/util/FileTools.java
=> Making FileTools.ensureCorrectDataFile() public

.github/workflows/build.yml
=> Bump Python version

src/com/xilinx/rapidwright/MainEntrypoint.java, src/com/xilinx/rapidwright/examples/PipelineGenerator.java, src/com/xilinx/rapidwright/examples/PipelineGeneratorWithRouting.java, src/com/xilinx/rapidwright/rwroute/PartialRouter.java, src/com/xilinx/rapidwright/rwroute/RWRoute.java, src/com/xilinx/rapidwright/rwroute/RWRouteConfig.java, test/src/com/xilinx/rapidwright/examples/TestExamples.java, test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
Corresponding tutorial update incoming:
https://www.rapidwright.io/docs/RWRoute_partial_routing.html
Step 2 should read:
`gradlew run --args="PartialRouter picoblaze_partial.dcp picoblaze_partial_routed.dcp --nonTimingDriven"`
=> Fix PartialRouter and PipelineGeneratorWithRouting tutorials

test/src/com/xilinx/rapidwright/device/TestNode.java
... for a node that Vivado returns nothing on too.
=> Test that Node.getAllUphillNodes() returns nothing

src/com/xilinx/rapidwright/router/RouteThruHelper.java, src/com/xilinx/rapidwright/util/FileTools.java, test/shared/com/xilinx/rapidwright/support/StringArrayConverter.java, test/src/com/xilinx/rapidwright/util/TestFileTools.java
New APIs to make RapidWright run standalone without the need to write to disk or download files.
=> New API to create a static set of data files

src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java, test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistReader.java
Fixes https://github.com/Xilinx/RapidWright/issues/626
Needs https://github.com/eddieh-xlnx/RapidWrightDCP/pull/20
=> [PhysNetlistReader] Throw exception if BEL conflict

src/com/xilinx/rapidwright/edif/EDIFNetlist.java, test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Otherwise EDIFPort's parent cells are not set correctly.
=> [EDIF] Expanded macros to be deep copied from prim library

src/com/xilinx/rapidwright/rwroute/RWRoute.java
`RWRoute.checkSinkRoutability()`
=> Refactor RWRoute's sink routability check into method

src/com/xilinx/rapidwright/util/ReportRouteStatusResult.java, src/com/xilinx/rapidwright/util/VivadoTools.java, test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java, test/src/com/xilinx/rapidwright/util/TestVivadoTools.java
=> Relevant tests to check against Vivado's report_route_status

test/src/com/xilinx/rapidwright/device/TestTile.java
This test fails because `Tile.getWireConnections()` throws an exception.
@clavin-xlnx Can you take a look please?
=> Add test for Tile.getWireConnections()

test/src/com/xilinx/rapidwright/util/TestReplaceEDIFInDCP.java
=> TestReplaceEDIFInDCP to copy DCP before replacing in-place

src/com/xilinx/rapidwright/design/DesignTools.java
This avoids dangling routed VCC branches later.
=> Removes the VCC A6 pin on 5LUT usages when removing cells

src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
for BELPins and SitePIPs, not just SitePins
=> [Interchange] PhysNetlistReader to create STATIC_SOURCE SiteInsts

src/com/xilinx/rapidwright/interchange/RouteBranchNode.java, test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
Partially fixes #789, from where testcase was derived.
=> [PhysNetlistWriter] Insert site port BELPin before site pin

src/com/xilinx/rapidwright/design/AltPinMapping.java, src/com/xilinx/rapidwright/edif/EDIFHierCellInst.java
Create a duplicate copy of `AltPinMapping` and `EDIFHierCellInst`
=> Add reference copy methods 

src/com/xilinx/rapidwright/util/CodeGenerator.java, test/src/com/xilinx/rapidwright/util/TestCodeGenerator.java
and site instances from a provided checkpoint
=> added static function that helps produce test nets (including PIPs)

src/com/xilinx/rapidwright/interchange/RouteBranchNode.java, test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
=> [PhysNetlistWriter] RouteBranchNode.getDrivers() to return input BelPin

src/com/xilinx/rapidwright/rwroute/RWRoute.java
Adds the alternative source to the SiteInst if it is used for routing.
=> [RWRoute] Only add alternative sources to SiteInst if used

src/com/xilinx/rapidwright/rwroute/RWRoute.java
This fixes two issues:
1) Properly resets `SitePinInst.isRouted()` flag in the initial loop
2) Removes the alternate source pin if it was previously routed but is no longer used.
=> [RWRoute] Properly remove dual-output pins and reset routed flag

src/com/xilinx/rapidwright/examples/PipelineGeneratorWithRouting.java
add an extra input variable to choose distance-based routing or timing-driven routing
=> fix a bug in PipelineGeneratorWithRouting.createPipeline()

src/com/xilinx/rapidwright/rwroute/TimingAndWirelengthReport.java, test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
=> Fix TimingAndWirelengthReport.main()

src/com/xilinx/rapidwright/router/RouteThruHelper.java, test/src/com/xilinx/rapidwright/router/TestRouteThruHelper.java
=> Add RouteThruHelper.isRouteThruPIPAvailable(Design, Node, Node) overload

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/eco/ECOPlacementHelper.java, src/com/xilinx/rapidwright/router/RouteThruHelper.java, test/src/com/xilinx/rapidwright/eco/TestECOPlacementHelper.java, test/src/com/xilinx/rapidwright/router/TestRouteThruHelper.java
Utility for aiding incremental placement of LUTs and FFs.
=> Add com.xilinx.rapidwright.eco.ECOPlacementHelper

src/com/xilinx/rapidwright/util/FileTools.java
Adds the timezone letter-code to `getTimeString()` and adds a sortable `getTimeStamp()` method.
=> Updates/adds timestamp APIs

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFNet.java
=> Fixes javadoc warnings related to angle brackets

src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java, src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java, test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
... on top of `[A-H]_O` to supply static sources.
=> [RWRoute] GlobalSignalRouting static net router to use [A-H]MUX outputs

src/com/xilinx/rapidwright/rwroute/RouterHelper.java, test/src/com/xilinx/rapidwright/rwroute/TestRouterHelper.java
Testing against DSP, BRAM, URAM and SLICEM.
=> RouterHelper.invertPossibleGndPinsToVccPins() to work on all invertible pins

src/com/xilinx/rapidwright/router/RouteThruHelper.java, test/src/com/xilinx/rapidwright/router/TestRouteThruHelper.java
Move assertions after a method which does null checking.
Expand tests, with more comments.
=> [RouteThruHelper] Move assertions, expand tests

README.md
Current link is broken, move to python3 setup for now.
=> Move mybinder link to Python3

src/com/xilinx/rapidwright/design/tools/LUTTools.java, src/com/xilinx/rapidwright/rwroute/RWRoute.java
=> [RWRoute] Do not pin swap SRL (shift register) cells

test/src/com/xilinx/rapidwright/design/TestDesignTools.java, test/src/com/xilinx/rapidwright/edif/TestEDIFHierPortInst.java
Of the five testcases in `TestEDIFHierPortInst.testGetRoutedSitePinInst()`, the last situation:
```
// Cell pin placed onto a E5LUT/O5 -- its net does not exit the site but
// another net is using EMUX
"processor/stack_loop[4].upper_stack.stack_pointer_lut/LUT5/O,null",
```
fails because it returns a SPI belonging to some other net.
There appears to be a similar method: `DesignTools.getRoutedSitePin()` which appears to behave correctly for all five testcases (except it returns a site pin name, and not a `SitePinInst` object).
=> Known failing test for EDIFHierPortInst.getRoutedSitePinInst()

src/com/xilinx/rapidwright/rwroute/RWRoute.java
Hoist source-pin-related-work outside the loop that deals with sinks.
=> [RWRoute] Tidy up createNetWrapperAndConnections()

src/com/xilinx/rapidwright/rwroute/RWRoute.java
Removal from https://github.com/Xilinx/RapidWright/pull/945
=> [RWRoute] When removing unused source SPI restore intra-site routing

src/com/xilinx/rapidwright/design/DesignTools.java
This is an attempt to fix the issue reported in #986.
=> [DesignTools] Fix NPE in calculateUtilization()

test/src/com/xilinx/rapidwright/device/TestNode.java
=> Test for wire/node mismatch reported in #983

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFNetlist.java
Also removes missed cells from encrypted modules inside the black box module to be removed.
=> [DesignTools.makeBlackBox()] Fixes an issue of removing CARRY blocks fed by routethrus

src/com/xilinx/rapidwright/util/JobState.java, src/com/xilinx/rapidwright/util/LSFJob.java
Adds UNKWN (unknown) for LSFJob status.
=> Adds UNKWN state for LSFJobs

src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java, test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
=> [RWRoute] Do not assume Y = 0 has Laguna tiles, since it could be HBM device

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/edif/EDIFHierPortInst.java, src/com/xilinx/rapidwright/timing/TimingGraph.java
Also emit a `WARNING: Unable to find physical pins on Net '<net>'; possibly due to encrypted netlist.`` message before eventually throwing a `RuntimeException`.
=> [RWRoute] Do not NPE on encrypted netlists

src/com/xilinx/rapidwright/util/VivadoTools.java
Fixes breakage by https://github.com/Xilinx/RapidWright/pull/1029.
Sorry!
=> [VivadoTools] Source *_load.tcl from same dir as DCP

src/com/xilinx/rapidwright/interchange/Interchange.java, src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java, src/com/xilinx/rapidwright/util/VivadoTools.java
=> Small Interchange/PhysNetlistReader/VivadoTools improvements

src/com/xilinx/rapidwright/interchange/LogNetlistReader.java, src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java, src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java, src/com/xilinx/rapidwright/util/Utils.java
- Adds necessary Versal IO types
- Manages some intra-routing issues to properly store the BELPins necessary to communicate site routing within Versal sites
- Turns off obsolete checks
=> [Interchange] Fixes to support Versal designs via Interchange

src/com/xilinx/rapidwright/rwroute/RouterHelper.java
By walking through the IMRs present.
=> [RouterHelper] invertPossibleGndPinsToVccPins() to support Versal LUTs

src/com/xilinx/rapidwright/examples/PolynomialGenerator.java, src/com/xilinx/rapidwright/gui/GUIModuleInst.java, src/com/xilinx/rapidwright/gui/TileScene.java, src/com/xilinx/rapidwright/placer/handplacer/HandPlacer.java
Cuts snapping distance in half, cleans up some of the code.
=> [HandPlacer] Cleanup snapping code in hand placer

src/com/xilinx/rapidwright/rwroute/RouteNode.java
Missed from https://github.com/Xilinx/RapidWright/pull/1098
=> [RWRoute] RouteNode.setType() to accept any locals

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/rwroute/RouterHelper.java, test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Plus a few other IMR-related fixes.
=> [DesignTools] foreachConnectedBELPin() to walk through Versal IMRs

src/com/xilinx/rapidwright/design/DesignTools.java, src/com/xilinx/rapidwright/router/UltraScaleClockRouting.java, src/com/xilinx/rapidwright/rwroute/PartialCUFR.java, src/com/xilinx/rapidwright/rwroute/PartialRouter.java, src/com/xilinx/rapidwright/rwroute/RWRoute.java, src/com/xilinx/rapidwright/rwroute/RouterHelper.java
Especially around locked PIPs.
=> [RWRoute] Minor cleanup 

.github/workflows/test-rapidwright-wrapper.yml
As it keeps intermittently failing
=> [Actions] Remove gradle/wrapper-validation-action

src/com/xilinx/rapidwright/edif/EDIFTools.java, test/src/com/xilinx/rapidwright/edif/TestEDIFTools.java
Fixes issue introduced in #1253
=> [EDIFTools] Fix connectPortInstsThruHier when finding source pin

.classpath, .github/workflows/build.yml, test/src/com/xilinx/rapidwright/design/TestSitePinInst.java
Should resolve #1274.  Also includes a minimal test.
=> [SitePinInst] Fix for getBELPin() for handling unplaced module instance creation

.classpath, .github/workflows/build.yml, test/src/com/xilinx/rapidwright/design/TestSiteInst.java, test/src/com/xilinx/rapidwright/design/TestSitePinInst.java
=> Fix to for errors related to SitePinInst removal of alternate site type pins
