Xilinx/RapidWright

- com/xilinx/rapidwright/edif/EDIFNetlist.java
Check and skip null pointer of an EDIFCellInst returned from a getCellInstFromHierName(...) call.
This was encountered while parsing an EDF exported by Vivado from a DCP.
> Skip null EDIFCellInst pointer

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
Sometimes, we could have different cells with the same EDIFName, e.g. when trying to generate pre-implemented modules, we can use different generic parameters to generate different entities, and thus different cells despite the same EDIFName (entity name). When we then try to use these modules (which contains different cells with the same EDIFName) in RapidWright, there would be a conflict, and errors occur. 
I propose a reasonable way to solve this problem, the way that instead of skipping migrating cells whose EDIFNames have already existed in the library, we add suffixes to the EDIFNames of new cells to distinguish, and thus all new cells could be migrated. 
However, there is a drawback of this way that even an entirely same cell could also be migrated and renamed as a "different" …
> Update EDIFNetlist.java: migrateCellAndSubCells()

- src/com/xilinx/rapidwright/timing/TimingGroup.java
I am working on integrating RapidWright timing with nextpnr. AIUI, there is no way at the moment to work out timing for an incomplete part of routing, which would be needed to provide some kind of timing model in the nextpnr database for the router to use and these functions seem to be helpful for. I appreciate this may not end up being as accurate as doing it on full nets, but this is only to provide a guide for the nextpnr router with Vivado still useful for signoff timing.
> TimingGroup: Make 'add' functions public

- src/com/xilinx/rapidwright/gui/NumberedHighlightedTile.java
Even if the text item is added to the scene after 'this' (the tile
highlighting), It may happen that the text item is drawn before the tile
highlighting. As such, the text will not be visible.
Usually, this would be automatically handled if the text item is created
as a child of 'this' (the tile highlighting).
However, this does not seem to be working in QtJambi and the text item
has to be created without a parent and manually added to the scene.
Instead, we manually set the Z value of the text item to be greater than
the highlighting, to ensure that it is always drawn above the highlighting.
Signed-off-by: Morten Borup Petersen <morten_bp@live.dk>
> Ensure that highlighted tile numbers are drawn above tile highlighting

- src/com/xilinx/rapidwright/design/tools/LUTTools.java
Instead of the actual size the ASCII value of the digit was used (for instance 51 instead of 3). So the configuration of LUTs was very slow because the equation was evaluated 2^51 times instead of 2^3 times.
This was fixed by not using the ASCII character value but to parse the value correctly.
> Fixed getLUTSize. Returns actual size instead of ASCII value

- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
@clavin-xlnx Is there a better way to detect a bad PIP besides catching the NPE from `new PIP`?
> Add some simple error checking on PIP path.

- interchange/DeviceResources.capnp
- src/com/xilinx/rapidwright/interchange/DeviceResources.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesExample.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/Enumerator.java
The schema indicates that the wire table is StringIdx, StringIdx: 
https://github.com/Xilinx/RapidWright/blob/58f91e011e449be78c09b3f4302b341396c7b57c/interchange/DeviceResources.capnp#L105-L108
This fixes the DeviceResourceWriter to match the schema.
> Fix various bugs in device resource generation

- src/com/xilinx/rapidwright/design/blocks/PBlockGenerator.java
The pull request: 
-> takes into account that 7 series and Ultrascale devices have a different number of CARRY_PER_CLE, RAMLUTS_PER_CLE, 	SLICES_PER_TILE.
-> considers that FF & Carry can be placed in a SLICE together with LUTS (including LUTRAM) => different method of computing required nr. of Slices
-> in case of horizontal density algorithm, it adds some checks to avoid endless loop in special cases. For example, if provided patterns are unfeasible (unfeasible meaning cases like dev.getSite("SLICE_X"+xr+"Y"+yd)=null)
> 7 series PBlock generation

- src/com/xilinx/rapidwright/ipi/BlockCreator.java
Without this change all module implementations load the same pblock file and thus have all the same pblock (at least metadata wise) instead of their implemented one.
> BlockCreator: fix loading wrong pblock

- src/com/xilinx/rapidwright/edif/EDIFLibrary.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
This is a collection of issues I encountered while merging some EDIFNetlists.
Without this PR, `migrateCellAndSubCells` leaves the design in a somewhat inconsistent state:
* If a cell is newly inserted to the netlist, CellInsts will refer to it
* If a cell of the same name is already part of the design, CellInsts will refer to the old Cell that is not part of the Netlist
This PR tries to fix that by always having CellInsts refer to the cell that is part of the netlist.
Some discussion pointers:
* `migrateCellAndSubCells` gets called from closed source code. Therefore I cannot change its function signature. I had to introduce a helper function. This is not needed when you are able to recompile the closed source. Should I leave it as is, or replace with a version that will only work with …
> Bugfixes for migrateCellAndSubCells

- src/com/xilinx/rapidwright/util/FileTools.java
When neither RAPIDWRIGHT_PATH is set, nor the resources are present on the classpath, a NullPointerException is thrown. This PR detects this case and prints an error message.
Normally, I would throw an exception here. However, exceptions seem to be frowned upon in RapidWright, so this PR just prints to `System.err`.
Kind Regards,
Jakob
> detect NPE from resource not found

- src/com/xilinx/rapidwright/device/PartNameTools.java
`PartNameTools.getPart` should find parts regardless of upper-/lowercase input.
This PR accomplishes this by normalizing all names to lowercase both before storing them and before looking them up.
> PartNameTools: Normalize Part Names to lower case

- src/com/xilinx/rapidwright/design/blocks/PBlockGenerator.java
Updated the computation of pblockCLEHeight. In original code, sliceMsRequired was divided by SLICES_PER_TILE. However, in case of 7 series, an M-type tile has only one M slice.
> Corrected pblockCLEHeight for 7 series

- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/LogNetlistReader.java
- src/com/xilinx/rapidwright/interchange/LogNetlistWriter.java
This matches the plain text annotations.
> Move strList in embedded primitive library to the root.

- README.md
- interchange/README.md
Since we want to keep `git pull` separate, then I think it may be a good idea to add it to the update instructions.
Signed-off-by: ReillyMcK <romckend@byu.edu>
> Adjust update instructions to include git pull

- src/com/xilinx/rapidwright/interchange/DeviceResources.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/LogicalNetlist.java
This extends the DeviceResources writer to populate the parameter format sections added in https://github.com/SymbiFlow/fpga-interchange-schema/pull/19 . @clavin-xlnx If you have review comments or changes you'd like to add to https://github.com/SymbiFlow/fpga-interchange-schema/pull/19 feel free to leave a review, and I'll open a new PR.
> Add parameter format

- src/com/xilinx/rapidwright/placer/blockplacer/BlockPlacer2.java
The temperature in the `BlockPlacer2` should never be `NaN`. If that ever happens, it can no longer reach the target temperature and loops endlessly. This PR adds checks to throw an exception if this situation occurrs.
It also fixes the reason this occurred: If no moves are accepted while determining the initial temperature, we divide by zero.
> avoid NaN temperatures in BlockPlacer2

- src/com/xilinx/rapidwright/design/ModuleInst.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/util/JobQueue.java
These are some random places where my broken designs caused `NullPointerException` crashes. This PR tries to improve these error messages.
Also include the number of Jobs yet to start in `JobQueue`.
> Better Messages in JobQueue, Exceptions

- src/com/xilinx/rapidwright/design/blocks/PBlock.java
- src/com/xilinx/rapidwright/design/blocks/PBlockGenerator.java
On Artix 7, DSP Sites are prefixed by "DSP48_" instead of "DSP48E2_". Instead of hardcoding the prefix, use the Site's getNameSpacePrefix.
> make PBlockGenerator compatible with Artix 7 DSPs

- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/EnumerateCellBelMapping.java
Once RapidWright `getPinMappingsP2L` is updated to be fixed per #143, these fixes are required to generate the right outputs to `DeviceResources`.
> Fix some bugs with DeviceResourcesWriter w.r.t. to EnumerateCellBelMapping.

- src/com/xilinx/rapidwright/interchange/EnumerateCellBelMapping.java
RAMB36E1 `WRITE_WIDTH_A=0 RAM_MODE=TDP` isn't modeled correctly, but other
widths appear to be working.
> Implement a interchange workaround for new parameter behavior.

- src/com/xilinx/rapidwright/design/ModuleInst.java
Previously, we used the location relative to the anchor to look up
corresponding SiteInsts. This broke on unplaced or overlapped modules.
> Change ModuleInst.getCorrespondingPin to lookup via name

- Makefile
also specify targeted java version
Signed-off-by: Jakob Wenzel <jakobw@xilinx.com>
> add dependencies in Makefile to avoid unneeded recompilations

- build.gradle
This is another attempt at getting Gradle to build Jar files, basically the same as #61, while (hopefully) addressing your issues with that PR.
Compiled classes are still kept in `/bin`. All other files Gradle creates (Manifest, Jar File, ...) end up in `/build`.
> fix jar build issues in gradle

- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/LogNetlistReader.java
- src/com/xilinx/rapidwright/interchange/LogNetlistWriter.java
This is the complement to SymbiFlow/fpga-interchange-schema#43.
The renaming is done while reading/writing the logical netlist structure itself, as the `hdi_primitives` name is expected to be used for the primitives library in a lot of the EDIF related code. Hopefully this is reasonable.
> interchange: Use fixed names for macro and primitive libraries

- src/com/xilinx/rapidwright/design/TileRectangle.java
So far, there is no representation of a Bounding Box of something like a Module or Port in RapidWright. This PR adds one.
> add Class to represent Bounding Boxes

- build.gradle
- settings.gradle
- src/com/xilinx/rapidwright/MainEntrypoint.java
This PR allows building RapidWright as a Gradle Application. These new tasks are available:
* `run`: Directly run RapidWright
* `installDist`: Create a Distribution containing all Java Code as well as Start Scripts. This task is confusingly named for people coming from make. It does not install anything. It only creates a distribution inside the build directory.
* `distZip`/`distTar`: Create a Zip/Tar from the Distribution.
Since we have many Main-Files in RapidWright, this PR also creates a new Single Entrypoint that delegates to the other main classes by looking at the first argument.
I just set the arguments to be the same as the class names. This is good for most classes, but may require some more thought for some classes like …
> Gradle: Allow Building as Application

- src/com/xilinx/rapidwright/ipi/BlockCreator.java
- src/com/xilinx/rapidwright/util/JobQueue.java
- src/com/xilinx/rapidwright/util/PerformanceExplorer.java
Instead of deciding between LocalJob and LSFJob in all places where a job is required, this PR provides a factory method that does encapsulates the checking.
Since `JobQueue.isLSFAvailable` will be run more often, this PR introduces some caching there.
> create single method for selecting Job Types

- src/com/xilinx/rapidwright/interchange/WireType.java
These aren't really part of the general, inter-tile routing graph, and are specifically used in the IOB->BUFG routing path so 'special' is more appropriate for these than 'general'.
> interchange: Mark GENERIC intent as special wire type

- src/com/xilinx/rapidwright/gui/TileScene.java
This fixes the issue raised at https://groups.google.com/g/rapidwright/c/YyEYI0Mebu8
Also initialize the image to black before drawing on it. For me, there were some artifacts in the image otherwise.
> Clear Cached Image in TileScene

- src/com/xilinx/rapidwright/interchange/ConstantDefinitions.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
Most of the work to find nodes that the interchange export was doing seems unnecessary, based on previous code I used for nextpnr-xilinx that seemed to find everything fine.
Performance for xc7a35t without:
```
==============================================================================
==                  Device Resources Dump: xc7a35tcpg236-1                  ==
==============================================================================
Load Device:     0.412s     64.791MBs
populateEnums:     0.097s      4.725MBs
SiteTypes:     0.063s      0.976MBs
TileTypes:     0.088s      2.053MBs
Tiles:     0.023s      0.004MBs
INFO: Building uncommon Wire->Node cache...
This might take a few seconds for large devices on the first call.  
It is generally triggered when getting the Node from an …
```
> interchange: Faster node discovery

- scripts/invoke_rapidwright.sh
This is a workaround for #190. I've tested it on all the Java versions I have locally (8, 10, 11, 15 and 16), in particular Java 8 being too old to support the option so testing the case where it isn't supported.
> invoke_rapidwright: Set --add-exports where supported

- .github/workflows/build.yml
This provides two ways to access Unit Test Results in Github:
* Publish a summary table as well as Stack traces for failed tests as a separate Job
* Gradle's HTML Report is archived and can be downloaded from the Build Summary Page
> Make Unit test results accessible in Github

- src/com/xilinx/rapidwright/interchange/WireType.java
These are all intents that are needed to connect between pins and global routing, so they must be 'special' rather than 'general'.
> interchange: Fix wire type categories for UltraScale+ clocks

- src/com/xilinx/rapidwright/device/EnumerateIOExpansions.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/interchange/DeviceResources.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/PhysicalNetlist.java
@gatecat @acomodi - This is an attempt to make the macro expansion map dependent on `IOStandard` settings in response to Issue #193.  In my testing, I could only find `OBUFDS` and `OBUFTDS` with `IOStandard` dependent expansions.  Do you have examples of others?  I might not be setting up the example designs properly in `EnumerateIOExapansions` for the `IBUFDS*` and `IOBUFDS*` cases.
> Updates interchange and makes macro expansion map IOStandard dependent

- src/com/xilinx/rapidwright/device/PartNameTools.java
- src/com/xilinx/rapidwright/edif/EDIFParser.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/util/FileTools.java
- src/com/xilinx/rapidwright/util/Installer.java
- test/com/xilinx/rapidwright/checker/CheckOpenFiles.java
- test/com/xilinx/rapidwright/checker/CheckOpenFilesExtension.java
- test/com/xilinx/rapidwright/design/TestDesign.java
- test/com/xilinx/rapidwright/design/TestEDIF.java
- test/com/xilinx/rapidwright/design/TestRelocation.java
This PR addresses multiple instances of File Descriptors not being closed. It includes simple testcases for writing out and reading back in both EDIF and DCP files without leaking file descriptors. As we don't have a way to test designs for equality, I just check for very obvious problems.
This PR is dependent on #197. Github's view for this PR will include all of #197's diff until that one is merged.
> correctly close leaked file descriptors

- src/com/xilinx/rapidwright/debug/DesignInstrumentor.java
- src/com/xilinx/rapidwright/debug/ILAInserter.java
- src/com/xilinx/rapidwright/debug/ProbeRouter.java
- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/design/Unisim.java
- src/com/xilinx/rapidwright/device/PartNameTools.java
- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFHierCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFHierNet.java
- src/com/xilinx/rapidwright/edif/EDIFHierPortInst.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFParser.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/examples/PolynomialGenerator.java
- src/com/xilinx/rapidwright/examples/PrintEDIFInstances.java
- src/com/xilinx/rapidwright/examples/SLRCrosserGenerator.java
- src/com/xilinx/rapidwright/ipi/BlockStitcher.java
- src/com/xilinx/rapidwright/router/Router.java
- src/com/xilinx/rapidwright/router/SATRouter.java
- src/com/xilinx/rapidwright/timing/TimingGraph.java
- src/com/xilinx/rapidwright/util/FileTools.java
- src/com/xilinx/rapidwright/util/Installer.java
- test/com/xilinx/rapidwright/checker/CheckOpenFiles.java
- test/com/xilinx/rapidwright/checker/CheckOpenFilesExtension.java
- test/com/xilinx/rapidwright/design/TestDesign.java
- test/com/xilinx/rapidwright/design/TestEDIF.java
- test/com/xilinx/rapidwright/design/TestRelocation.java
Previously, `EDIFHierCellInst` stored all hierarchy as a single String. When we accessed hierarchy info, we had to re-parse the string every time. This PR replaces the internal representation of `EDIFHierCellInst` with an Array of `EDIFCellInst`.
This provides a speedup for `EDIFNetlist.getParentNetMap` while simultaneously decreasing memory usage. It also fixes #188.
This PR is dependent on #198. Github's view for this PR will include all of #198's diff until that one is merged. As #198 currently fails testing, this one does as well.
> Use EDIFCellInst instead of String hierarchy in EDIFHier classes

- src/com/xilinx/rapidwright/edif/EDIFCell.java
Fix the issue uncovered in #209
> fix crash in EDIFCell.getAllLeafDescendants

- build.gradle
* Increase Heap Limit in Unit tests from 512MB to 5GB. This should fix the failure on master.
* For newer Java Versions, apply the workaround identified by @gatecat in #190 to `run`, `install` and `test` tasks.
> Gradle improvements

- src/com/xilinx/rapidwright/design/Port.java
- src/com/xilinx/rapidwright/design/RelocatableTileRectangle.java
- src/com/xilinx/rapidwright/design/SimpleTileRectangle.java
- src/com/xilinx/rapidwright/design/TileRectangle.java
The class TileRectangle I introduced in #166 was not relocatable. This PR adds the class `RelocatableTileRectangle` which stores references to the actual tiles and can therefore be relocated across the fabric.
This new class is slightly slower than the old one. If you don't need relocatability, the old one should still be used. Therefore, I kept it under the name `SimpleTileRectangle`.
> Introduce relocatable rectangle of tiles

- src/com/xilinx/rapidwright/debug/DotEdifDumper.java
- src/com/xilinx/rapidwright/debug/DotGraphDumper.java
- src/com/xilinx/rapidwright/debug/DotPhysicalDumper.java
- src/com/xilinx/rapidwright/debug/DotSiteDumper.java
This adds classes to dump our different representations of designs as Graphviz Dot graphs. Their output has already been very useful to me in diagnosing problems. There are classes to dump these representations:
* EDIF Cells
* Physical Netlists
* SiteInsts
Instances can be filtered to limit the generated graphs to the area of interest.
> add classes to dump site insts, edif or physical netlists as dot graphs

- build.gradle
This makes the update_jars task visible in Gradle's task list (can be viewed by running `./gradlew tasks`).
> gradle: add group and description to update_jars task

- Makefile
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
There is a limit of calls to the GH API to get the jars' link. This results in failures while running a CI system that spawns several jobs that do require updating the jars.
This can be overcome by providing the link externally, which can be generated once for all the jobs that do require it, thus preventing reaching the API call limit.
> make: update jars: link from var to prevent API call limit 

- src/com/xilinx/rapidwright/edif/EDIFPort.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- test/com/xilinx/rapidwright/edif/TestEDIFPort.java
> Adding convenience methods to EDIFPort to get internal nets

- .github/workflows/build.yml
- build.gradle
- common.gradle
Mainly, moving the dependency and testing stuff into `common.gradle` which is included back.
> Refactor gradle to facilitate other gradle parents

- .github/workflows/build.yml
- .github/workflows/publish-test-results.yml
> Switching to SHA instead of tags for non-GitHub authored Actions.

- .classpath
- .github/workflows/build.yml
> Switch to Python 3.6 because of CI failures

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- test/com/xilinx/rapidwright/design/TestDesign.java
I agree with #117 that having two `EDIFCellInst` methods that are synonyms of each other is not particularly useful. 
This is the second of two proposed fixes, and is the riskier option.
`EDIFCellInst.setCellType(EDIFCell)` renamed to `setCellTypeRaw(EDIFCell)` (latter is not used, but kept around just in case it is useful in the future)
`EDIFCellInst.updateCellType(EDIFCell)` renamed to `setCellType(EDIFCell)`
with `updateCellType()` marked as `@deprecated` while still calling the new `setCellType`.
~The reasoning here is that one should never update the cell type without updating the port references of its portInsts. The only exception I'm not terribly confident about is:~
https://github.com/Xilinx/RapidWright/blob/7177e016ad6c1beefb1778d5a80aab7a468f4b3f/src/com/xilinx/rapidwright/desig …
> Fix #117 by setCellType doing what updateCellType did

- src/com/xilinx/rapidwright/edif/BinaryEDIFReader.java
- src/com/xilinx/rapidwright/edif/BinaryEDIFWriter.java
- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- test/com/xilinx/rapidwright/edif/TestBinaryEDIF.java
Aims to provide a binary equivalent to text-based EDIF that is an order of magnitude smaller in file size and 5-10X faster to load.  Should include an optional switch to cache loaded text-based EDIF.
> Binary EDIF Format 

- common.gradle
> Bumping version of jupyter_kernel for JeroMQ update to 0.5.2

- src/com/xilinx/rapidwright/tests/CodePerfTracker.java
- src/com/xilinx/rapidwright/util/CountingOutputStream.java
- test/com/xilinx/rapidwright/design/TestDesign.java
Also optimize `CountingOutputStream` by overriding the array variants of `write`.
> Test >4GB EDIFs are writeCheckpoint-able (needs >=14GB)

- src/com/xilinx/rapidwright/util/ParallelismTools.java
Setting the environment variable `RW_PARALLEL` to not zero means to enable parallelism.
Doing so means that ` pool.prestartAllCoreThreads();` gets called, but `pool` has not yet been initialized, so juggle the ordering.
> Fix for RW_PARALLEL != 0

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/edif/EDIFHierCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFHierPortInst.java
- src/com/xilinx/rapidwright/edif/EDIFNet.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- test/com/xilinx/rapidwright/edif/TestEDIFHierCellInst.java
- test/com/xilinx/rapidwright/edif/TestEDIFTools.java
Improves and makes more robust EDIFTools.connectPortInstsThruHier() by leveraging the EDIFHierCellInst rewrite last year.  
> Rewrite of EDIFTools.connectPortInstsThruHier() 

- src/com/xilinx/rapidwright/design/DesignTools.java
This was originally included in #385, but it has been isolated here as its own PR.
> Allows copyImplementation() to work with a dest top cell.

- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFChange.java
- src/com/xilinx/rapidwright/edif/EDIFChangeNet.java
- src/com/xilinx/rapidwright/edif/EDIFChangeType.java
- src/com/xilinx/rapidwright/edif/EDIFNet.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFPort.java
- test/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
- test/com/xilinx/rapidwright/edif/TestEDIFTools.java
This adds a capability to the logical netlist to keep track of `EDIFCell` objects that are modified by monitoring basic APIs.  It does not consider cells that have their name changed or to switch to a different library as a trigger for tracking.
> First cut at tracking logical cell changes

- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
* Add `EDIFCellInst.equals()` override
* `EDIFNetlist.getParentNetName()` to be sensitive to `parentNet == null`
> EDIFCellInst and EDIFNetlist small fixes

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/com/xilinx/rapidwright/design/TestDesignTools.java
This ensures that the `SiteInst.getNetFromSiteWire()` is updated correctly, on top of unrouting the (directly-connected) intra-site sitewire as done currently.
What remains to be done is to rip up any indirectly-connected sitewires too (e.g. those behind a site PIP)
> DesignTools.batchRemoveSitePins() to do SitePinInst.detachSiteInst()

- src/com/xilinx/rapidwright/edif/EDIFLibrary.java
During what seems like some rare circumstances, the ordering of cells on export can mistakenly find a false dependency if the library is not checked.  This ensures the library is checked as part of the new ordering so that identically named cells aren't mistaken.
> Fix netlist issue when ordering cells for export

- .github/workflows/build.yml
- common.gradle
- src/com/xilinx/rapidwright/util/ParallelismTools.java
When running in the `mybinder.org` Docker, only a single processor core is allocated to run the Jupyter Notebook.  The parameters to `ThreadPoolExecutor` were not legal and was throwing an `IllegalArgumentException`:
```
jshell> import com.xilinx.rapidwright.util.ParallelismTools;
jshell> ParallelismTools.get
get(            getParallel()
jshell> ParallelismTools.getParallel()
|  Exception java.lang.ExceptionInInitializerError
|        at (#2:1)
|  Caused by: java.lang.IllegalArgumentException
|        at ThreadPoolExecutor.<init> (ThreadPoolExecutor.java:1293)
|        at ThreadPoolExecutor.<init> (ThreadPoolExecutor.java:1215)
|        at ParallelismTools.<clinit> (ParallelismTools.java:67)
|        ...
```
This fixes the issue.
> Fix thread pool for single processor case

- test/src/com/xilinx/rapidwright/design/TestDCPLoad.java
Requires a new release to resolve the `NoSuchFileException` that is currently emitted when doing so.
> Add test for Vivado 2022.1 DCP

- src/com/xilinx/rapidwright/edif/EDIFTools.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFTools.java
This PR fixes an issue in `EDIFTools.uniqueifyNetlist()` (refactored from `EDIFTools.flattenNetlist()`) where it would fail to uniqueify cells that had parent cells that were also being uniqueified.
> Fix for uniqueify netlist (previously flatten netlist)

- src/com/xilinx/rapidwright/edif/EDIFName.java
- src/com/xilinx/rapidwright/edif/ParallelEDIFParser.java
- src/com/xilinx/rapidwright/edif/ParallelEDIFParserWorker.java
* Lower the initial size of HashMaps to conserve space
* The parallel EDIF parser did not uniquify port inst names
> Save some memory in EDIF

- src/com/xilinx/rapidwright/debug/ILAInserter.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/examples/PicoBlazeArray.java
- src/com/xilinx/rapidwright/util/RelocateModulesIntoBlackboxes.java
- test/src/com/xilinx/rapidwright/design/TestDesign.java
- test/src/com/xilinx/rapidwright/design/TestModuleInst.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Since in the new release, `Module.addModule()` (called by `Module.createModuleInst()`) will copy the Module's netlist into the Design's netlist.
Supersedes #418.
Fixes a small bug in `EDIFTools.copyCellsAndSubCells()` whereby it would throw an exception if it encountered cells from the primitives library that it had not copied in.
Also removes now-redundant `EDIFNetlist.migrateCellsAndSubCells()` and `ModuleInst.getCellInst().setCellType()`.
> Test for Design.createModuleInst() copying Module's EDIFNetlist

- test/src/com/xilinx/rapidwright/design/TestDesign.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
Test that ensures `Design.copyCell()` identifies proper alternate site type for the destination `SiteInst` if it does not already exist.
> Test for copyCell() fix from #419

- test/shared/com/xilinx/rapidwright/support/CheckOpenFilesExtension.java
This is an attempt to fix the spurious failures we see in the open files checker.
My theory is that Java is doing something in the background that needs file IO. Those handles are only open for a very short time. If the `Files.list` call happens to land in that exact timeframe, those handles are included in the result. When we call `Files.readSymbolicLink`, the handle is already closed. The call fails with an exception. Right now, we return the file handle's virtual filename. This exact timing probably does not happen twice for one testcase, so the list of open files differs before and after the testcase. This leads to a testcase failure.
This PR changes the behaviour to ignore those file handles.
> Open files checker: Ignore file descriptors that fail to resolve to actual files

- common.gradle
- src/com/xilinx/rapidwright/util/Job.java
- src/com/xilinx/rapidwright/util/JobQueue.java
* Move printing of last log lines into Job class
* Allow not printing job command (generates large amount of logs if using together with Job.setRapidWrightCommand)
* Increase max tests memory if not running on Github
> Jobqueue improvements

- .github/workflows/build.yml
- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
The `Cell` object will soon store `EDIFHierCellInst` instead of `EDIFCellInst`.  This change corresponds to that update.
> Changes to correspond to Cell updates

- src/com/xilinx/rapidwright/util/Installer.java
> Fix Installer to direct to GitHub Discussion and updated debian pkg

- src/com/xilinx/rapidwright/design/ModuleInst.java
The method was previously always assuming the context of `this` for the `ModuleInst`.  This fix resolves the issue by incorporating the proper instance.
> Fixes oversight in connect for ModuleInsts

- src/com/xilinx/rapidwright/edif/EDIFHierNet.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFHierNet.java
This contains two changes to support the ECO flow.
1. A new method that gets all leaf port insts on an EDIFHierNet
2. Fixes to EDIFTools.connectPortInstsThruHier()
> Get all leaf port insts for a given EDIFHierNet

- src/com/xilinx/rapidwright/edif/AbstractEDIFParserWorker.java
Some older EDIF files have properties on the Design.  This is a work-around fix that allows the EDIF to be parsed successfully.
> Work-around for old EDIF

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
RWRoute attempts to build a symmetric clock spine around the logic to be routed.  In doing this, it attempts to split the covered region into two (an upper part and lower part).  In the case that the logic doesn't span outside a single clock region, this was failing because it was a clock region up against the edge of the device and the default case of only a single 'half' being addressed was not consistent.
> Fix Symmetric Clk Router for Single Clock Region Case

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Rather than into the work library, if source library doesn't exist in destination netlist.
Fixes #512.
> EDIFNetlist.{copy,migrate}CellAndSubCells() to copy into new same-named library

- src/com/xilinx/rapidwright/device/IOStandard.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
Fixes an issue with an `OBUF` to `OBUFDS_DUAL_BUF` expansion in an UltraScale+ part and properly handles it when `DEFAULT` is set to the voltage standard.
> Fixes macro expansion for exceptional case

- src/com/xilinx/rapidwright/design/tools/RelocationTools.java
- src/com/xilinx/rapidwright/examples/RelocateHierarchy.java
Makes some changes to support relocation of an entire DCP (top level) by providing the empty string `''` as an argument to the hierarchy prefix parameter.  Also enables a command-line option to augment the set of `SiteTypeEnum` types that are to be relocated.
> Enables top-level relocation, custom site type list

- src/com/xilinx/rapidwright/util/PerformanceExplorer.java
Allows users to specify cell names to be constrained by pblock rather than the entire design.
> PerformanceExplorer: Adds optional cell names to be constrained in pblock

- src/com/xilinx/rapidwright/design/DesignTools.java
This PR fixes two issues:
1) When copying the implementation from one design to another, previously, `SitePinInst` objects were not re-created.  Normally this was not an issue as generally the design would quickly be written to a DCP which doesn't capture `SitePinInst` objects, Vivado will infer them based on routing and site routing.  However, the lack of these pins was obscuring the fan out calculation of nets when exporting the routing for a DCP and was incorrectly writing out the node tags such that messages in Vivado upon DCP read would appear, such as:
```
WARNING: [Designutils 20-5375] Skipping invalid subTree.
CRITICAL WARNING: [Designutils 20-205] Net hierarchical/net/name was unrouted during load.
```
This change adds the `SitePinInst` objects as part of the copy of the …
> Fixes for copyImplementation()

- src/com/xilinx/rapidwright/util/Installer.java
Supersedes https://github.com/Xilinx/RapidWright/pull/487 since that doesn't apply cleanly anymore.
-----
This fixes a Zip-Slip vulnerability.
This change does one of two things. This change either
1. Inserts a guard to protect against Zip Slip. OR
2. Replaces `dir.getCanonicalPath().startsWith(parent.getCanonicalPath())`, which is vulnerable to partial path traversal attacks, with the more secure `dir.getCanonicalFile().toPath().startsWith(parent.getCanonicalFile().toPath())`.
For number 2, consider `"/usr/outnot".startsWith("/usr/out")`. The check is bypassed although `/outnot` is not under the `/out` directory. It's important to understand that the terminating slash may be removed when using various `String` representations of the `File` object. For example, on Linux, `println(new …
> vuln-fix: Zip Slip Vulnerability

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
Fixes issues related to issues in `HardwareContractMaker` in #390.  This accommodates scenarios where the top level hierarchy object is being used.  Also fixes an issue when creating a stand-alone netlist from an existing cell was not updating the top cell reference appropriately.
> Fixes for copy cell to DCP

- src/com/xilinx/rapidwright/design/ModuleInst.java
When a module instance is placed, it may contain GND and VCC routing.  Because GND and VCC are global nets in a design, the subset of routing PIPs that are in the net need to be relocated during placement, but not the rest of the PIPs.  In the case of moving a module instance, the existing placed PIPs should be relocated (removed and then re-added with the proper offset) and leave all other existing GND/VCC PIPs in place.  This PR attempts to accomplish this.  This may diminish performance for re-placement heavy designs with modules that contain VCC and GND routing.
> Better manage GND/VCC routing of module instances during placement

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Seems like #543 didn't quite do the job for the case where a bidir PIP lands on a sink node.
> Fix DesignTools.getTrimmablePIPsFromPins() for bidir sink nodes

- src/com/xilinx/rapidwright/interchange/LogicalNetlistToEdif.java
This PR adds the new class `LogicalNetlistToEdif` which implements a CLI utility for converting FPGA Interchange Logical Netlists to EDIF format.
> LogicalNetlist -> EDIF converter

- test/src/com/xilinx/rapidwright/design/TestSiteInst.java
Unlike previous tests, this is without LUT6 being already occupied such that LUT5 was the only choice.
> Test for routing thru LUT5 to get to CARRY[48].DI

- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
- test/src/com/xilinx/rapidwright/design/TestNet.java
... and test that `Net.removePin()` with `preserveOtherRoutes` set works correctly on static nets too.
> Test that Net.removePin() unsets Net.alternateSource

- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFNet.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- src/com/xilinx/rapidwright/edif/EDIFPortInstList.java
By itself, this PR doesn't change the existing EDIF parser behaviour; it just provides the capability to defer sorting and the ability to perform that sort at some later point.
> Support to enable netlist parser to sort EDIFPortInstList at end

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/edif/BinaryEDIFWriter.java
- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFPort.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFPort.java
Fixes #560, which describes a change in `EDIFPort.getBusName()` behaviour introduced in #547.
This PR adds an overload `EDIFPort.getBusName(boolean)` which determines whether the open bracket is preserved. The existing parameter-less method defaults to false, preserving old behaviour. Cases where the open bracket is needed to differentiate between bussy and bitty ports will call the new overload with `true`.
> Restore original EDIFPort.getBusName() behaviour

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Specifically rewriting: `DesignTools.getTrimmablePIPsFromPins()` and modifying `DesignTools.unrouteSourcePin()`.
Also removes unused private method `DesignTools.unroutePin()`
Since it wasn't handling the two new testcases with bidirectional PIPs.
In this rewrite, use `PIP.isReversed()` to get the correct driving/sink node.
> Rewrite unroute source/sink pin methods in DesignTools

- src/com/xilinx/rapidwright/tests/CodePerfTracker.java
Also, only update maxSegmentNameSize if !printProgress.
Means that we get this output now:
```
==============================================================================
==                                 Example                                  ==
==============================================================================
XML Parse & Device Load:     1.106s              |    632.809MBs (peak)
(EDIF Parse):            (    0.446s) |    772.668MBs (peak)
(Read PhysDB Caches):            (    0.075s) |    791.926MBs (peak)
(Read PhysDB Routing):            (    0.082s) |    827.535MBs (peak)
(Read PhysDB Placement):            (    0.088s) |    827.551MBs (peak)
(Read PhysDB Finalizing):            (    0.006s) |    827.551MBs (peak)
Read Netlist & PhysDB:     0.624s              | …
```
> [CodePerfTracker] Don't +1 in computing maxSegmentNameSize

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Handle cases where:
* 5LUT is being used as a static source, necessitating the A6 input to be tied to VCC.
* RAMS32 is mapped onto a SLICEM LUT, also necessitating A6 to be tied to VCC
* SRL32CE was transformed into a SRL16E, requiring A6 to be tied to GND
> DesignTools.createA1A6ToStaticNets() fixes

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
As occurring for single-ported distributed RAM block, where the read and write addresses are identical. Thus, a pins on the logical "read/write address" is mapped onto both the `WAx` (write) and `Ax` (read) physical pins. Since the write address site pin is shared between all RAMs in the SLICEM, make sure that the read address site pin is also identified correctly.
> DesignTools.createMissingSitePinInsts() to handle logical -> multiple phys pins

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
> Determine if a Net is driven by a hierarchical port, created as part of an out-of-context synthesis flow, for example.
It is important for a router to identify such nets, and to reserve their site pin nodes, lest those nodes are claimed during the routing of other nets. When this happens, Vivado will flag it up as a conflict.
> Add DesignTools.isNetDrivenByHierPort() method

- src/com/xilinx/rapidwright/edif/AbstractEDIFParserWorker.java
- src/com/xilinx/rapidwright/edif/EDIFParser.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/edif/ParallelEDIFParser.java
- src/com/xilinx/rapidwright/util/FileTools.java
- src/com/xilinx/rapidwright/util/function/InputStreamSupplier.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFParser.java
This will allow the EDIF Parser (both serial and parallel) to accept gzipped EDIF files for parsing.  It adds this capability by checking the file extension, if it ends with `.gz`, it is assumed gzip compressed and will temporarily decompress it in the same directory as the original file and parse it.  Once parsing is completed, the temporary decompressed EDIF file is deleted.  This will overwrite an existing EDIF file if the provided `.edf.gz` file is given for parsing.
> Add support to parse gzipped EDIF files

- src/com/xilinx/rapidwright/edif/AbstractEDIFParserWorker.java
- src/com/xilinx/rapidwright/edif/EDIFParser.java
- src/com/xilinx/rapidwright/edif/ParallelEDIFParser.java
- src/com/xilinx/rapidwright/util/Params.java
- src/com/xilinx/rapidwright/util/function/InputStreamSupplier.java
- test/src/com/xilinx/rapidwright/edif/ParallelEDIFParserTestSpecificOffsets.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFParser.java
There is a tradeoff when using gzipped EDIF files that, because RapidWright has a very fast parallel parser, decompressing onto disk first is much faster (~2x or more).  However, this temporarily uses ~18x more disk space in order to do so.  This change makes the default method to decompress (more slowly) in memory in order to prevent out of disk space errors.  If users would like the additional parsing speed with gzipped EDIF, they can set the parameter `RW_DECOMPRESS_GZIPPED_EDIF=1` (either via an Environment Variable or through the jvm command line `-Dname=value` parameter).
> Make loading gzipped EDIF decompress in memory by default, on to disk by option

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Currently, if a LUT routethru services more than one cell (e.g. LUT output fans to two FFs) then only one `EDIFHierPortInst` will be returned.
Fix this here.
> DesignTools.getPortInstsFromSitePinInst() to cope with LUT RTs

- src/com/xilinx/rapidwright/edif/EDIFHierNet.java
- src/com/xilinx/rapidwright/edif/EDIFNet.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFHierNet.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFTools.java
* Add `EDIFHierNet.getPortInsts()` -- helper for returning `EDIFHierPortInst`-s built from the result of `EDIFNet.getPortInsts()`
* Add `EDIFHierNet.getSourcePortInsts()` -- helper for returning `EDIFHierPortInst`-s built from the result of `EDIFNet.getSourcePortInsts()`
* Add `EDIFTools.createUniquePort()`
* Add `EDIFTools.connectPortInstsThruHier(EDIFHierNet, EDIFHierPortInst, String)` overload
* Miscellaneous null checks
> EDIF Improvements

- src/com/xilinx/rapidwright/edif/EDIFPort.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
This fixes an issue when RapidWright writes out an EDIF netlist that contains a cell with two ports, one bussed and the other a single bit that have the same root name, for example:
```
my_port
my_port[1:0]
```
This is a legal set of ports, but when the EDIF is exported from RapidWright, the EDIF rename collides on port instance references.  This PR resolves the issue by explicitly using the `busName` of the `EDIFPort` for any bussed ports which contains a trailing `[` character that then gets translated to an `_` when it is legalized for EDIF.  This differentiates it from its single bit counterpart.
> Handle EDIF export bussed port name collision with identically named bit ports

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/NodeStatus.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeInfo.java
Static net router to now reuse existing used resources when performing partial routing.
Refactor `RouteNode` functionality into `RouteNodeInfo`, fixing coordinate and wirelength computations as well as improving clarity and robustness.
> [RWRoute] Static net router + RouteNode enhancements

- src/com/xilinx/rapidwright/edif/EDIFTokenizer.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFParser.java
When parsing a gzipped EDIF, we can only estimate its uncompressed size in order to decide where each worker thread should start parsing. The possibility exists that estimate is so incorrect, and when there are enough workers, that one worker is asked to start at an offset that is past the end of the uncompressed file.
Handle this situation, and improve the tests to catch this.
> [EDIF] Fix for skipping past EOF, improve tests

- src/com/xilinx/rapidwright/design/tools/RelocationTools.java
Now that routethru cells are distinguished by their routethru flag, the `RelocationTools` check was no longer handling the routethrus correctly.
> Fixes RelocationTools to correspond to new Cell.equals() behavior

- test/src/com/xilinx/rapidwright/device/TestBEL.java
Test to ensure `BEL.isFF()` does not return true for any RBELs.
> Test for isFF()

- test/src/com/xilinx/rapidwright/design/TestDesign.java
Works for 2022.2, fails on 2022.1 (expects `"this.is.an\\\\.escaped\\\\.identifier"` instead).
This was the input description:
```
module top(input a, b,
input \this.is.an\.escaped\.net\.identifier ,
output o);
wire \this.is.another\\.escaped\$net\+&!identifier ;
(* DONT_TOUCH="true" *)
LUT2 \this.is.an\.escaped\.cell\.identifier (.O(\this.is.another\\.escaped\$net\+&!identifier ), .I0(\this.is.an\.escaped\.net\.identifier ), .I1(a));
(* DONT_TOUCH="true" *)
LUT2 \this.is.another\\.escaped\$cell\+&!identifier (.O(o), .I0(\this.is.another\\.escaped\$net\+&!identifier ), .I1(b));
endmodule
```
> Test for Cell-s and Net-s with backslashes in name

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
Imitate how Vivado represents `SLICE` `SRST*` connections by clearing out the intra site routing when connected to GND (i.e. no sensitivity to set or reset). This allows `DesignTools.createCeSrRstPinsToVcc()` to create the corresponding `SitePinInst` and attach to the VCC net, using the in-built inverter to achieved ground.
> [Interchange] PhysNetlistReader to align with Vivado on SRST routing

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/placer/handplacer/ModuleOptimizer.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Also fixes an issue where there was a discrepancy between Vivado's report_utilization numbers and RapidWright.  RapidWright was counting routethru cells when Vivado does not.
> Augments calculateUtilization to also accept a pblock, adds test

- src/com/xilinx/rapidwright/examples/PipelineGeneratorWithRouting.java
Consequence of https://github.com/Xilinx/RapidWright/pull/615 which can cause `OutOfMemoryError`.
> Clear out PipelineGeneratorWithRouting static members

- src/com/xilinx/rapidwright/util/DataVersions.java
- test/src/com/xilinx/rapidwright/device/TestUnisimPlacements.java
This is to address the issue found in #631, points to an updated unisim data file with Versal Premium unisim placement information added.
> Add missing Versal Premium unisim placements

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Fix for https://github.com/Xilinx/RapidWright/pull/646 whereby if an `EDIFCellInst` inside of a macro is found, it is possible that this instantiation is not unique and may lead to a conflicting IOStandard error.
If inside a macro, use the outer macro's `EDIFCellInst` instead.
> Fix EDIFNetlist.cellInstIOStandardFallback

- src/com/xilinx/rapidwright/interchange/DeviceResourcesExample.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/EnumerateCellBelMapping.java
This adds an option (`--skip_route_resources`) to `DeviceResourcesExample` that will skip adding wires and nodes to the device model FPGA Interchange file.  Currently there are a couple of issues (#410, also see https://github.com/Xilinx/RapidWright/issues/176#issuecomment-1030410003) that would prevent large designs from being written out with routing.  
This also fixes a performance bug that caused the `Cell <-> BEL pin map:` phase to take almost 20 minutes, with this change it now takes about 2 minutes.
The output from a run with the following parameters:
`java -Xmx32000m com.xilinx.rapidwright.interchange.DeviceResourcesExample xcvu19p --skip_route_resources`
```
Prims&Macros:     0.812s     65.209MBs          |   1652.207MBs (peak)
Cell <-> BEL pin map:   140.047s      0.565MBs …
```
> Enables large FPGA Interchange devices for placement

- test/src/com/xilinx/rapidwright/design/TestNet.java
Discovered in https://github.com/Xilinx/RapidWright/issues/635.
> Test for invalid pin name with Net.createPin()

- test/src/com/xilinx/rapidwright/design/TestSitePinInst.java
Discovered in https://github.com/Xilinx/RapidWright/issues/635.
Depends on https://github.com/eddieh-xlnx/RapidWrightDCP/pull/21
> Test for SitePinInst.getRouteNode() failure

- src/com/xilinx/rapidwright/design/blocks/PBlockGenerator.java
In more recent utilization reports, some lines appear more than once and overwrite the original parsed values.  This is a quick fix to avoid this issue.
> Fix PBlockGenerator Parser

- src/com/xilinx/rapidwright/examples/SLRCrosserGenerator.java
- src/com/xilinx/rapidwright/router/UltraScaleClockRouting.java
- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
* `GlobalSignalRouting`/`UltraScaleClockRouting` to accept predicate for determining preserved resources (so it may avoid them) during clock routing
* `UltraScaleClockRouting` to track visited nodes so that they are not visited again
* `UltraScaleClockRouting` to stop considering routethrus
* `GlobalSignalRouting`'s clock router to not route above the centroid if there's no sinks there -- otherwise creating an antenna
* `PartialRouter` constructors to have `softPreserve` argument
* `PartialRouter`'s `softPreserve` argument to also be used for global clock routing (setting it to true allows clock router to use preserved resources, and any nets previously using such resources will be rerouted)
* `PartialRouter`'s entrypoints to accept null for the `pinsToRoute` parameter; in this case, …
> RWRoute fixes

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/examples/SLRCrosserGenerator.java
- src/com/xilinx/rapidwright/router/UltraScaleClockRouting.java
- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
Instead of just removing the non-parent physical `Net` after moving over all sitewires, move all of its `SitePinInst`-s too.
Built on top of https://github.com/Xilinx/RapidWright/pull/655
> DesignTools.makePhysNetNamesConsistent() to move SitePinInst-s too

- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
For preserving backward compatibility, omitted from https://github.com/Xilinx/RapidWright/pull/655.
> Add PartialRouter.routeDesignWithUserDefinedArguments() overload

- src/com/xilinx/rapidwright/util/DataVersions.java
- test/src/com/xilinx/rapidwright/device/TestUnisimPlacements.java
In a new release, all family unisim placement data will be aliased by architecture upon load of the `unisim_data.dat` file.  This will minimize the needed size of the file and provide broader coverage automatically.
> More compact data file, all family coverage with comprehensive test

- src/com/xilinx/rapidwright/interchange/EdifToLogicalNetlist.java
There's an easy way to convert LogicalNetlist to EDIF (https://github.com/Xilinx/RapidWright/pull/565), but there's no easy way to do it the other way around.
This PR adds a capability to do that.
> EDIF -> LogicalNetlist converter

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
Address issue in #632 by detecting upfront if a targeted device is supported by RWRoute.
> Fix for #632 - Detect unsupported RWRoute devices

- src/com/xilinx/rapidwright/design/ModuleInst.java
- test/src/com/xilinx/rapidwright/design/TestModuleInst.java
Without this, any `SitePinInst`-s associated with the `ModuleInst` which were previously on an old net will remain there, while the pin is also inserted into the new net.
> ModuleInst.connect() to move SitePinInst-s from old Net to new

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
`DesignTools.createCeSrRstPinsToVCC()` to now create a `SRST[12]` site pin connected to the VCC net if the FF cell's sitewire is empty or connected to the GND net.
Also revert the `postProcess()` method of https://github.com/Xilinx/RapidWright/pull/636 which wrongly created the environment for triggering the old behaviour for adding this site pin.
Add support for UltraScale parts too.
> DesignTools.createCeSrRstPinsToVCC() to detect gnd to invert

- test/shared/com/xilinx/rapidwright/support/CheckOpenFilesExtension.java
- test/src/com/xilinx/rapidwright/TestCheckOpenFilesInstalled.java
PR #397 modified the gradle environment such that every testcase is automatically extended with methods to ensure the test closes all of the files it opens. However when run outside of gradle (e.g. in an IDE) the testcase that checks to see if this extension is running obviously fails. This commit adds a conditional to skip the test if run outside of gradle.
> Ignore TestCheckOpenFilesInstalled.test if outside of gradle

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Before this, a macro cell in the global/singleton macro library was only shallow-copied into a netlist's private primitive library.
As part of macro expansion, the child instances of a macro are also updated to instantiate cells in the netlist's private library. However, because the instance list was only shallow copied, this ended up modifying the global macro's instance list too.
The end result was that the global macro library now holds a reference to a particular user netlist, which blocks it from being garbage collected.
> [EDIF] More expanded macros to be deep copied from prim library

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
.. plus optimize `expandMacroUnisims()`.
Currently, the following scenario is not considered:
* Design has `OBUFDS` cell instantiations
* Only some of those `OBUFDS` cells are expanded into `OBUFDS_DUAL_BUF`
* Collapsing causes the `OBUFDS_DUAL_BUF` cell to be renamed to `OBUFDS`, without awareness that `OBUFDS` already exists.
* Now there are two `OBUFDS` cells being instantiated in the netlist, but only one in the library.
> [EDIF] EDIFNetlist.collapseMacroUnisims() to not clobber cell

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/router/Router.java
- src/com/xilinx/rapidwright/util/DeviceTools.java
- src/com/xilinx/rapidwright/util/MessageGenerator.java
- src/com/xilinx/rapidwright/util/StringTools.java
Adds a `StringTools` API to enable printing a list of Strings in columns and uses that in `MainEntrypoint` to print a list of applications using columns instead of a long list.  For example, the new output is:
```
Need one argument to determine the mode. Valid modes are (case-insensitive):
AddSubGenerator               DeviceResourcesExample        IsolateLeafClkBuffer          PBlock                        ReportDevicePerformance     
BlockCreator                  EDIFNetlist                   JobQueue                      PerformanceEvaluation         ReportTimingExample         
BlockStitcher                 EDIFParser                    Lesson1                       PerformanceExplorer           Router                      
BlockUpdater                  EDIFPropertyValue …
```
> MainEntrypoint to print application list in columns

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Using `EDIFPropertyValue.equals()` instead of `==`.
> [EDIF] Explicit DEFAULT IOStandard on Cell to be overriden by Net

- .gitignore
- Makefile
- bin/rapidwright
This is to allow users to add `$RAPIDWRIGHT_PATH/bin` to their `PATH` so they can run RapidWright from any directory.
> Add symlink to rapidwright wrapper in bin

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
Discovered by https://github.com/Xilinx/RapidWright/pull/691 which changed `RWRoute.staticNetsAndRoutingTargets` to be an `IdentityHashMap` which has a non-deterministic iteration order.
This exposed a bug whereby the static net router would -- when routing static nets in a particular order -- allow one static net to overuse a node that was actually the pin-node for the other static net.
Fix this oversight, and make static net routing deterministic.
> [RWRoute] Fix routeStaticNets() to not use other nets' nodes

- build.gradle
It appears that recent `module` files generated by `gradle` have not been valid due to an issue with the test-fixtures plugin (see #697).   This change removes the test-fixtures from the published release to avoid this problem.  
This issue seems loosely related to https://github.com/gradle/gradle/issues/14936.  
This will require a new release to fix the publicly available jars.
> Fix published maven central jar by omitting test-fixtures

- .github/workflows/test-rapidwright-wrapper.yml
- bin/rapidwright
Found by @zakn-amd.
It appears that the new `rapidwright` wrapper on Linux changes the current working directory (to the root of the git repository) , thus when an application writes to the current directory it appears there as opposed to where it was invoked.
> Linux RapidWright wrapper to not change working directory

- src/com/xilinx/rapidwright/design/DesignTools.java
Code common between this and `DesignTools.fullyRemoveCell()` has been refactored into `DesignTools.fullyUnplaceCellHelper()`.
> Add DesignTools.fullyUnplaceCell()

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
By transforming logical static nets named `<const{0,1}>` into physical static nets `GLOBAL_LOGIC{0,1}`
Fixes #701.
CC: @haydenc-amd
> Fix DesignTools.makePhysNetNamesConsistent() 

- src/com/xilinx/rapidwright/design/DesignTools.java
Pulled out from #708, necessary for testing the next release.
> DesignTools.makePhysNetNamesConsistent() to copy before modifying

- src/com/xilinx/rapidwright/util/VivadoTools.java
- test/src/com/xilinx/rapidwright/util/TestVivadoTools.java
CC: @zakn-amd 
For catching scenarios where Vivado exits abruptly -- e.g. it was unable to read the DCP.
> VivadoTools.runTcl to throw exception if exitcode != 0

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
* Allow `Net.USED_NET` in assertion, since it can appear as a placeholder anywhere.
* Disable onerous `assert(spi.getNet() == net)` for now
> [PhysNetlistWriter] Relax assertions

- test/src/com/xilinx/rapidwright/design/TestSitePinInst.java
When `SitePinInst` being detached is not actually the SPI that is attached to the `SiteInst`.
> Test that SitePinInst.detachSiteInst() preserves sitewire

- src/com/xilinx/rapidwright/router/RouteThruHelper.java
`Path.of()` appeared in Java 11 and is not in Java 1.8, the equivalent is `Paths.get()`.  This is not caught in `gradlew` or Eclipse when setting compiler compliance to 1.8.  This was only detected with using a 1.8 JDK.
> 1.8 compliance

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/util/DataVersions.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
In a DCP design created from https://github.com/litex-hub/linux-on-litex-vexriscv, there were instances of `IOBUFDSE3` which would have a child instance of `OBUFTDS_DCIEN` that would also get expanded to `OBUFTDS_DCIEN_DUAL_BUF`.   RapidWright was not handling this previous to this PR.  This updates the data file to include `OBUFTDS_DCIEN_DUAL_BUF` and changes the expansion correctly.
> Multilevel macro expansion

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/interchange/DcpToInterchange.java
For conversion of DCP into a Logical and Physical Interchange netlist, along with (normal) XDC constraints.
Also accessible through `rapidwright DcpToInterchange` due to addition to `MainEntrypoint`.
> Add DcpToInterchange class

- src/com/xilinx/rapidwright/design/DesignTools.java
Look at the non-hier logical net name to determine if it's a static net.
https://github.com/Xilinx/RapidWright/pull/703 previously only considered `<const{0,1}>` logical nets in the top cell; this PR considers their appearance in any cell.
Greater discussion should be had as to whether we should rely solely on the assumption that all logical nets with a name of `<const{0,1}>` are GND/VCC nets. A more robust solution would be to examine the this logical net to find its source pin, and make sure it really is driven by the `GND` or `VCC` primitive; however, this would be a linear search on every single processed net.
We could take a shortcut and use a different assumption that static nets must be driven by a cell instance called `GND` or `VCC` (allowing a binary search into …
> DesignTools.makePhysNetNamesConsistent() to consider */<const{0,1}>

- src/com/xilinx/rapidwright/design/DesignTools.java
> DesignTools.makePhysNetNamesConsistent() to use hier name

- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
1. PartialRouter's global router -- when `softPreserved` is enabled -- currently allows it to use any node preserved by any othernet. Amend it so that input pin nodes (identified through its associated `RouteNode`) cannot be repurposed.
2. For hier-ports (i.e. out of context top-level inputs), create input pin nodes so that the global router cannot steal them. Not doing so causes Vivado to flag a conflict, presumably because a future net would have no chance of getting to that pin.
> PartialRouter's global router to not unpreserve sink nodes

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/design/tools/LUTTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Improves the behavior of `DesignTools.makeBlackBox()` such that is more cleanly removes site routing when a black boxed components removed cells share sites with logic that will remain in the design.  This adds a new method that aims to correctly unroute site routing for a given pin of a placed and routed cell.
> Unroute site routing when removing a cell

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
`MultiCellPinMapping` is only populated if `PinMapping.isOtherCell()` is true -- where `PinMapping` is the Interchange object we're currently in the process of constructing.
Further, it looks like every alt-pin-mapping should have an other cell so `MultiCellPinMapping` should be unconditionally set.
> [Interchange] Fix PhysicalNetlist's MultiCellPinMapping

- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
PartialRouter currently supports (fully) re-routing clocks like the base RWRoute, with one exception: when `softPreserve` is enabled, its clock router is allowed to "steal" resources from existing routing that would otherwise be preserved.
Afterwards, PartialRouter will examine the clock routing and unpreserve those nets that now need rerouting, and correctly preserve clock resources so that they can't be used again.
This PR fixes a flaw in this process where a "victim" net has already been unpreserved before, which would otherwise cause it to fail.
> [RWRoute] Fix PartialRouter for when clk node already unpreserved

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
It appears to be legal for a DCP to contain a design with multiple GND and/or VCC nets, rather than having just one of each with the canonical name `GLOBAL_LOGIC[01]`.
`DesignTools.makePhysNetNamesConsistent()` will now merge the former into the latter.
> DesignTools.makePhysNetNamesConsistent() to merge static nets too

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
CC @zakn-amd 
Fixes #738, with test based on smaller of the two attached testcases. Both exhibit the same failure where `DesignTools.createCeSrRstPinsToVCC()` was trying to work on a Laguna flop.
> DesignTools.createCeSrRstPinsToVCC() to skip non-SLICE FFs

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
... when using non-tied-node sources (e.g. LUTs).
It appears that `Design.readCheckpoint()` does this for (fully-routed) static nets loaded from DCP, it makes sense that we do this when routing ourselves too.
Maintaining this invariant can also make the determination of non-tied-node static sources more efficient. An example would be `DesignTools.unrouteGNDNetAndLUTSources()` from #760, as well as for #762.
> GlobalSignalRouting.routeStaticNet() to create output SPIs

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/edif/EDIFNet.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/timing/TimingGraph.java
- src/com/xilinx/rapidwright/util/MakeBlackBox.java
- When creating a blackbox from the command line, also will prohibit partially used half slices from being used as it seems the Vivado placer struggles to put cells in those locations without considering downstream congestion issues
- Adds lock_design methods  (netlist, placement and routing) that attempt to mimic the `lock_design -level {netlist, placement, routing}` Tcl command in Vivado.  Some minor variations exist, but should accomplish the same end
> Shell creation improvements to enable lock_design and timing closure preservation

- src/com/xilinx/rapidwright/util/DataVersions.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Fixes #748 by updating `unisim_data.dat` with the appropriate setting for `IS_CLK_INVERTED`.
> Fix 748 - Updates RAM32X1S property to correct default

- src/com/xilinx/rapidwright/design/ModuleInst.java
- test/src/com/xilinx/rapidwright/design/TestModuleInst.java
Some tiles around IO columns can have certain nodes depopulated from the standard set.  This breaks the relocatability of some modules when the routes use those nodes in other contexts.  This change detects the depopulated nodes and ensures the module cannot be placed in those locations.
For example: 
The tile `INT_X94Y899` in the `xcvu13p` device is fully populated:
However, the tile `INT_X74Y589` in the same device is not:
> Fix module relocation in the face of tile node depopulation

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Prior, the only method was `DesignTools.getRoutedSitePinFromPhysicalPin()` which (a) only returned the first site pin, and (b) returned the other output site pin by adding it to the `Net` and thus having a side effect which has caused problems.
This side effect was actually causing an assumption in RWRoute (that the `COUT` pin was always the primary source, with a `HMUX` pin a possible alternate) to break since `DesignTools.getRoutedSitePinFromPhysicalPin()` actually set `HMUX` as the primary source. 
Note that `DesignTools.createMissingSitePinInsts()` -- which calls `DesignTools.getRoutedSitePinFromPhysicalPin()` -- will now not infer any dual output pins. If those are needed, they can be explicitly gotten, as RWRoute does.
> Add DesignTools.getAllRoutedSitePinsFromPhysicalPin()

- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- test/src/com/xilinx/rapidwright/rwroute/TestRouterHelper.java
e.g. `COUT` on the uppermost row of the device.
> Fix RouterHelper.projectOutputPinToINTNode() for depop pins

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
Previously, RWRoute was not setting the isReversed() flag on `PIP` objects.  This PR makes it so that all `PIP`s are properly set.  This also found that when routing static nets, the `PIP` creation process was using a less efficient method as it was presenting the connection nodes in order (rather than reverse order in typical routing).  This also modifies how static `PIP`s are created to present the driver/load ordering correctly.
> Set reversed flag on bi-directional PIPs used from end->start

- src/com/xilinx/rapidwright/design/DesignTools.java
* Make `DesignTools.handlePinRemovals()` a public method.
* `DesignTools.updatePinsIsRouted(Net)` to clear routed state of all `SitePinInst`s and return immediately if no PIPs.
* Add `DesignTools.updatePinsIsRouted(Design)` variant.
> Small DesignTools improvements

- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
* RWRoute to ignore the `GLOBAL_DUMMY_ROUTE` net
* `postRouteProcess()` and `saveRouting()` to be more robust with swapped sources
* `PartialRouter.determineRoutingTargets()` to stash the `RouteNode.prev` pointer when attempting to recover existing routing on connections, in order to prevent backtracking to the wrong source.
> RWRoute improvements

- src/com/xilinx/rapidwright/design/tools/RelocationTools.java
As documented in https://github.com/eddieh-xlnx/RapidWrightDCP/pull/25.
Needs `RelocationTools.relocate()` to be fixed to handle stub PIPs too.
> Update to fixed microblazeAndILA_3pblocks.dcp

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesign.java
Including one which has no pins (but does have intra-site routing).
Also eliminate redundant sitewire operations in `DesignTools.makePhysNetNamesConsistent()`.
> Add test for Design.movePinsToNewNetDeleteOldNet()

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
- test/src/com/xilinx/rapidwright/design/TestCell.java
Built on #813.
An incoming release will create `Cell` objects for FF routethrus.
`DesignTools.createCeClkOfRoutethruFFtoVCC()` and `PhysNetlistWriter` have been adapted to take advantage of this/fixed to work with this new feature.
A test for such cells is also present.
> Fixes necessary to take advantage of/fix for FF routethru cells 

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
Since PhysNetlistReader always consumes it, even if not bidir:
https://github.com/Xilinx/RapidWright/blob/7cec5122cab9359b532701dd97bafd74b2a94baa/src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java#L564-L566
> [PhysNetlistWriter] Set PhysPIP.setForward() even if not bidir

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
The `IO.IO` site port BELPin is actually an input site pin/output site port BEL pin. When an OUTBUF instance is present in the IOB site, the `OUTBUF_O` sitewire appears to be driven by the `OUTBUF.O` BEL pin as well as by the `IO.IO` site port. This cannot be true, so omit the `IO.IO` site port when its corresponding `SitePinInst` is not present.
> [PhysNetlistWriter] No IO site port output BELPins without SitePinInst

- src/com/xilinx/rapidwright/router/UltraScaleClockRouting.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
* `RWRoute.saveRouting()` to detect invalid traced-back solutions
* `UltraScaleClockRouting` to disallow going from a `VROUTE` node back to a `HROUTE` node.
> Minor RWRoute and UltraScaleClockRouting fixes

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFHierPortInst.java
In #826, it was found that a recent change had caused some child macro cell types to not have the proper netlist reference in their library.  This change deep copies those children cells to ensure they point back to the parent netlist.
> [EDIFNetlist] - Ensure Macro Expansion Deep Copies Children 

- src/com/xilinx/rapidwright/design/DesignTools.java
By remove the a Node's `fanouts` immediately from the map, we are inherently more robust to the presence of loops. This is possible because each node should only be visited once anyway.
This also means we don't need to track and avoid bidirectional PIPs separately, since we can no longer visit nodes more than once.
> Simplify and make DesignTools.updatePinsIsRouted() more robust

- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
Currently, the PartialRouter has two modes of operation:
1. Provide a list of pins to route
2. Ask it to infer a list of pins to route
Item 2 is rather simplistic in that it seeks out those nets that no PIPs, and tries to route all its pins. Partially routed nets with PIPs and some unrouted pins are not picked up. This PR resolves this by employing `DesignTools.updatePinsIsRouted()` (added in https://github.com/Xilinx/RapidWright/pull/762) as part of 2 (specifically, during `PartialRouter.preprocess()`) in order to identify which pins it needs to route.
A second change in this PR is for PartialRouter to support incremental clock routing, which kicks in if there are unrouted pins on a clock net, and that clock net is partially routed. (If the clock net is entirely unrouted, use the …
> PartialRouter preprocessing and clock routing improvements

- Makefile
Fix for when the output of `$(shell ...)` being too long to be captured by a variable.
> Replace $(shell ...) with $(wildcard) and $(subst) in Makefile

- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
In the upcoming release, there has been a change in how `SitePinInst` objects are inferred from the placement and routing information. Specifically, this change infers these pins much more conservatively (arguably, correctly) such that some pins that were previously picked up may now be omitted and require an examination of the logical (EDIF) netlist to restore.
This change is necessary to cope with routing solutions that have have conflicted nodes leading to site pins.
Updates tests where this situation occurs.
> Update tests to infer missing SitePinInsts

- src/com/xilinx/rapidwright/design/tools/RelocationTools.java
- test/src/com/xilinx/rapidwright/design/TestRelocationTools.java
Fixes #393 too, a feature that is no longer relevant as of #808.
> RelocationTools fixes and more robust testing

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/eco/ECOTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Specifically, when trying to find the routed site pin of a physical cell, use the actual intra-site net after checking that it is indeed an alias (by checking that they both have the same parent net)
> DesignTools.createMissingSitePinInsts() to cope with net aliases

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Specifically, aware of top-level ports that are `inout`s.
Prior to this PR, both `EDIFNetlist.generateParentNetMap()` and `EDIFNetlist.getNetAliases()` would only consider top-level `input` ports, and never `inout` ports when determining parent nets and thus physical pins.
Fix this by consider `inout` ports as being a fallback parent net drivers (i.e. when there is no other parent net).
~Depends on https://github.com/eddieh-xlnx/RapidWrightDCP/pull/26~
> EDIFNetlist.{generateParentNetMap,getNetAliases}() to be inout-aware

- src/com/xilinx/rapidwright/eco/ECOTools.java
Not identifying aliases means that it fail to exit the site.
> ECOTools.createExitSitePinInst() to detect net aliases

- src/com/xilinx/rapidwright/design/DesignTools.java
This PR restructures the way `DesignTools.addProhibitConstraint()` adds the XDC Tcl command.  It previously batched up all the `get_bels` calls into a single monolithic one--with the thinking that it would be faster.  However, this is not the case.  Instead, it is faster to set the property for each bel individually.  Here is a quick comparison of DCP load times for the DCP in our [shell tutorial](https://www.rapidwright.io/docs/ReusingTimingClosedLogicAsAShell.html#creating-a-shell):
| DCP Type | Vivado Load Runtime |
| ----------- | ----------- |
| Batched BEL `set_property` (prior to this PR)     | 6m4s  |
| Individual BEL `set_property` (this PR)   | 1m22s |
| Binary Netlist+Constraints File (future work) |  37s |
> Faster prohibit constraint

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RWRouteConfig.java
Specifically, it's been observed that when RWRoute operates on a hard design requiring many routing iterations to resolve congestion, its `presentCongestionFactor` can grow to such large values that overusing any node will inflate the path cost such that all other factors (distance to sink) cannot be captured using single-precision floating point causing the routing algorithm to fly blind. In particular, with `presentCongestionMultiplier` having a default value of 2, within 20 or so iterations, the [units-in-the-last-place](https://en.wikipedia.org/wiki/Unit_in_the_last_place) rises to 1.0 (`Math.ulp((float) Math.pow(2, 23)) == 1.0`).
Cap the `presentCongestionFactor` value using a heuristic that depends on the wirelength weight since RWRoute scales the distance to sink by this value: …
> Cap RWRoute.presentCongestionFactor to prevent accuracy loss

- src/com/xilinx/rapidwright/util/CodeGenerator.java
- test/src/com/xilinx/rapidwright/util/TestCodeGenerator.java
Creates a method to generate RapidWright code to reproduce a single `Net`.  Also fixes some redundant generation of `SiteInst` in the `CodeGenerator`.
> Add convenience method for Net code gen, fix redundant code

- src/com/xilinx/rapidwright/router/RouteThruHelper.java
- test/src/com/xilinx/rapidwright/router/TestRouteThruHelper.java
The site pin `H[1-6]` on `SLICEM`s are both the read address for the `H[56]LUT` as well as the write address `[A-H][56]LUT` distributed RAMs.
Prior to this PR, querying RouteThruHelper for whether a `H[1-6]` -> `H_O` routethru is possible would fail if there was any other LUT cell (`[A-G][56]LUT`) in the same site.
> Fix RouteThruHelper.isRouteThruPIPAvailable() for SLICEM.H[1-6]

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
Replace #724 with a more general rule to skip the `IO` site pin for all IOB tiles, since I've discovered at least one case (`A28`/`IOB_X0Y47` on an xcvu3p) where the `IO` site pin does have a node feeding it (which appears to be driven by the `HPIOBDIFFOUTBUF_X0Y22/AOUT` pin) which I've never seen used.
Also update the `TestDesignTools.testCreateMissingSitePinInstsInout()` test to remove the harmless site pin that was previously created.
> DesignTools.createMissingSitePinInsts() to skip "IO" on IOB sites

- src/com/xilinx/rapidwright/design/DesignTools.java
... if they have been/will be analyzed anyway.
Reduces occurrences of this warning:
https://github.com/Xilinx/RapidWright/blob/56d9bd4aaaf24da885540fb0141d7e2b8aaeb4fa/src/com/xilinx/rapidwright/design/DesignTools.java#L2097-L2109
and potentially even reduces redundant work done too.
> DesignTools.createMissingSitePinInsts(Design) to skip non-parent nets

- build.gradle
This removes the warning from Gradle:
```
Execution optimizations have been disabled for task ':jar' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: 'RapidWright/bin'. Reason: Task ':jar' uses this output of task ':restoreScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own …
```
> Declare gradle dependency explicitly

- src/com/xilinx/rapidwright/eco/ECOTools.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- test/src/com/xilinx/rapidwright/eco/TestECOTools.java
ECO to insert a cell inline based on a specific input pin.  Method signature:
```
public static Cell createInlineCellOnInputPin(Design design, EDIFHierPortInst input,
Unisim reference, Site site, BEL bel, String logInput, String logOutput)
```
For example:
The magenta colored LUT1 was inserted along with the cyan colored net to connect it to the existing input pin.  
Also added a few convenience methods.
> [ECOTools] Inline cell insertion

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/eco/ECOTools.java
- src/com/xilinx/rapidwright/util/MakeBlackBox.java
When creating a shell DCP as in the [Reuse Timing-closed Logic As A Shell](https://www.rapidwright.io/docs/ReusingTimingClosedLogicAsAShell.html) tutorial, sometimes certain designs will experience unroutable situations (or antennas) resulting from certain Vivado behaviors and the implementation state of the shell DCP.  This PR fixes at least some of those issues:
1. Previously, when `Net` objects needed to be renamed, some of the `SitePIP` objects were removed inadvertently.  This resolves this issue by using `Net.rename()` rather than `DesignTools.updateNetName()` which does not preserve the site pip routing.
2. There is a rare scenario when a black box is created and one of its outputs drives a flip-flop in a SLICE and the default site input bypass pin `[A-H][X|_I]` is being consumed …
> [DesignTools.makeBlackBox()] Fixes routing issues in makeBlackBox()

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
- test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
When a `LUT` is used as a static source that only feeds an intra-site sink (e.g. `CARRY8`) the LUT output was not recognized as a driver pin and thus the static net assignment on `[A-H]_O` was not being propagated when the result was read back.
> [PhysNetlistWriter] Recognize static source BELPins (e.g. LUT outputs)

- src/com/xilinx/rapidwright/design/tools/LUTTools.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
For distributed RAM cells placed onto a `H` BEL, its `A` (read address) and `WA` (write address) must be shared. Thus if we want to swap its `A`, we must also swap its `WA` in sync, which is beyond the our current `LUTTools` capabilities.
This does not affect distributed RAMs placed onto the `A`-`G` BELs since their `A` and `WA` are not shared -- we are still free to swap their `A` inputs (just as if they were read-only LUTs) and still prevented from swapping its `WA`, just as before.
> [RWRoute] Don't swap dist RAMs on 'H' BELs since A and WA are shared 

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
The IOB BEL pin `PAD.PAD` is a bidirectional pin, owing to the fact that IOBs are configurable between being an input or an output *(or even bidirectional)*.
Now I haven't got a bidir testcase handy, but at least for input configurations its necessary that the `PAD.PAD` pin is an output that serves as a routing source.
To determine if it should be treated as an output pin, look at whether the following site PIP is enabled:
* `PADOUT` for the UltraScale/UltraScale+ series
* `IUSED` for the 7 series
> [PhysNetlistWriter] Infer direction of IOB's PAD.PAD BEL pin

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
- src/com/xilinx/rapidwright/interchange/RouteBranchNode.java
- test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
Previously, the following stubs exist:
* On GND nets, the BELPin `SLICE_X?Y?/HARD0GND.0` would always be present for every slice in the design. Omit it as it's almost always unused (has no branches) and even if it was used, adds no value since it's an always-on static source.
* On static (mostly VCC) nets, PIPs that originate from a static source (e.g. `INT_X?Y?/VCC_WIRE`) were being recognized as stubs, when they should be sources.
> [PhysNetlistWriter] Fix stubs on static nets

- src/com/xilinx/rapidwright/interchange/PhysNetlistWriter.java
Observed in the `corundum_25g` benchmark of the [FPGA24 Routing Contest](https://xilinx.github.io/fpga24_routing_contest/) (which targets the `xcvu3p` device) it turns out there are a number of pads inside `GTY` tiles, namely:
* `IPAD[12]` pads in `GTYE4_CHANNEL` sites, which contain output BEL pins that were accidentally dropped from the written physical netlist.
* `REFCLK[01][NP]` pads in `GTYE4_COMMON` sites, which are bidir: 
In this case, check to see if the `OBUFDS[01]_GTYE4` cell (lower left of the selected sitewire, not present in this example) is present to determine its direction.
> [PhysNetlistWriter] Handle PORT cells in GTY tiles

- src/com/xilinx/rapidwright/interchange/PIPCache.java
- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
Be a little more tolerant of invalid PIPs that have valid tiles and valid wires, but no PIP exists between them.
> [PhysNetlistReader] Warn and omit if PIP not found

- src/com/xilinx/rapidwright/design/tools/LUTTools.java
Warn and ignore, rather than die cryptically with an NPE.
> LUTTools.swapLutPinsFromPIPs() to warn when site pin not found

- src/com/xilinx/rapidwright/design/DesignTools.java
For cases where the `EDIFNetlist`'s physical pins is null (e.g. encrypted cells) then only create an output `SitePinInst` if it is driven by a `Cell`.
This prevents the problem of additional `SitePinInst`s being added to a `Net` when a routethru is necessary to reach a `Cell` (e.g. LUT routethru to get to `CARRY8`). More details in this thread: https://github.com/Xilinx/fpga24_routing_contest/discussions/59#discussioncomment-8054698
> DesignTools.createMissingSitePinInsts() to infer SitePinInsts more smartly

- src/com/xilinx/rapidwright/design/compare/DesignComparator.java
- src/com/xilinx/rapidwright/design/compare/DesignDiff.java
- src/com/xilinx/rapidwright/design/compare/DesignDiffType.java
- src/com/xilinx/rapidwright/edif/compare/EDIFNetlistComparator.java
- test/src/com/xilinx/rapidwright/design/compare/TestDesignComparator.java
A tool to help compare two design's place and routing data.  
Example usage:
```java
Design gold = Design.readCheckpoint("gold.dcp");
Design test = Design.readCheckpoint("test.dcp");
DesignComparator dc = new DesignComparator();
// Set desired flags, there are 3: 
//   1) dc.setComparePlacement(default: true)
//   2) dc.setComparePIPs(default: true)
//   3) dc.setComparePIPFlags(default:false)
int numOfDiffs = dc.compareDesigns(gold, test);
// Optionally print a summary
dc.printDiffReportSummary(System.out);
```
> DesignComparator - compares place and route data

- .classpath
- .github/workflows/build.yml
- src/com/xilinx/rapidwright/device/WireInterface.java
- src/com/xilinx/rapidwright/device/WireObject.java
- test/src/com/xilinx/rapidwright/device/TestWireInterface.java
This update will take a few steps, but getting the interface in place first has no dependencies.  
In a future release, `Node` and `Wire` objects would implement this interface.
At a minimum, it would allow us to collapse `RouteThruHelper.isRouteThruPIPAvailable(Design, Node, Node)` and `RouteThruHelper.isRouteThruPIPAvailable(Design, Wire, Wire)`.
> Create a common interface for Node and Wire Objects

- src/com/xilinx/rapidwright/rwroute/Connection.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraphTimingDriven.java
- src/com/xilinx/rapidwright/rwroute/TimingAndWirelengthReport.java
- src/com/xilinx/rapidwright/timing/TimingManager.java
Rather than keeping a reference to `Node`, extend it to save 16 bytes per `RouteNode` when in compressed OOP mode:
* -4 bytes from the `RouteNode.node` reference no longer being needed
* -12 bytes from the `Node` compressed object header (8 bytes mark + 4 bytes class) being redundant now that it is combined with the `RouteNode` object.
> [RWRoute] RouteNode to extend Node

- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFCellInst.java
- src/com/xilinx/rapidwright/edif/EDIFHierCellInst.java
- test/shared/com/xilinx/rapidwright/support/RapidWrightDCP.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFCell.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFCellInst.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFHierCellInst.java
Add the ability to determine if an `EDIFHierCellInst` is unique across the netlist, with a view to enabling algorithms (such as #910) to decide whether it is safe to modify.
To answer the `EDIFHierCellInst.isUniquified()` question, we need to know whether all `EDIFCellInst`-s that make up `EDIFHierCellInst` are themselves individually unique (folded, non-hierarchical) instantiations across the netlist.
To answer this `EDIFCellInst.isUniquified()` question, we need to track how many `EDIFCellInst`s exist for each `EDIFCell` which is also implemented in this PR.
Take for example the hierarchical path:
```
top/foo/bar/baz
```
To determine if it's safe to modify the `baz` instantiation (i.e. to change its parameters/LUT masks, or to change its port connections) we must determine that its …
> Add EDIFHierCellInst.isUniquified()

- src/com/xilinx/rapidwright/design/tools/LUTTools.java
* `DesignTools.swapMultipleLutPins()` to ignore `SRL*` cells (since shift registers cannot have their pins swapped)
* `DesignTools.swapSingleLutPins()` to also swap alt pin mappings (populated for intra-site LUT routethrus, e.g. to get to a FF)
> [LUTTools] LUT pin swapping fixes

- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
https://github.com/Xilinx/RapidWright/issues/756
> Known failing test for #756 (GlobalSignalRouting)

- test/src/com/xilinx/rapidwright/device/TestTile.java
On VU3P:
```
get_sites -of [get_tiles LAG_LAG_X30Y250]
WARNING: [Vivado 12-3731] No sites matched '*'
```
On VU5P:
```
get_sites -of [get_tiles LAG_LAG_X30Y250]
LAGUNA_X6Y140 LAGUNA_X6Y141 LAGUNA_X7Y140 LAGUNA_X7Y141
```
whereas RapidWright currently returns sites for all four testcases (the first three of which is incorrect).
Discovered during the analysis of https://github.com/Xilinx/RapidWright/issues/738 which uses the VU3P (not that nextpnr should place a regular `FDRE` onto a Laguna BEL, even if there was a valid site)
> Known failing test for Tile.getSites() result different to Vivado

- src/com/xilinx/rapidwright/design/DesignTools.java
Otherwise any cached logical `EDIFHierNet` becomes a stale reference to an old net.
Expected to be fixed in an upcoming release.
> Temporary workaround to clear logical netlist after Net.rename()

- src/com/xilinx/rapidwright/edif/EDIFHierPortInst.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
Previously, the `checkConstantRoutingAndNetNaming()` builds a mapping between hierarchical-cell-pin-name to physical-net. Later, `checkNetTypeFromCellNet()` does a lookup from a non-hierarchical-cell-pin name to find its corresponding physical-net. 
Fix it so that `checkNetTypeFromCellNet()` is hierarchy-aware.
> [PhysNetlistReader] Fix checkConstantRoutingAndNetNaming()

- src/com/xilinx/rapidwright/edif/EDIFPropertyValue.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFPropertyValue.java
`EDIFPropertyValue.getBooleanValue()` to try parse an integer even if it's a `STRING` type and not throw an NPE.
> [EDIFPropertyValue] Fix getBooleanValue() NPE

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
To be conservative, do not allow GlobalSignalRouter to update any intra-site routing, including those sitewires corresponding to site pins.
This means that we can no longer fracture existing user LUTs (placed at `[A-H]6LUT`) so that the `[A-H]5LUT` can serve as a static source, losing some of the routability benefits provided by https://github.com/Xilinx/RapidWright/pull/914, but in return being more robust.
Quantifying this loss in `TestGlobalSignalRouting.testRouteStaticNet()` operating on `optical-flow.dcp`:
* Number of static ground sources before: 1952, now: 1858 (-4.8%)
* Number of static ground PIPs before: 39777, now: 39827 (+0.13%)
> [GlobalSignalRouter] No intra site routing for new static source pins

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
This prevents `*_O` and `*MUX` from being used for two different static sources, and also prevents *`_O` from being later used as a LUT routethru (support for which was added in #932).
Along the lines of https://github.com/Xilinx/RapidWright/pull/953 which unwound modification of intra-site routing for static nets.
> [RWRoute] Preserve [A-H]_O node when [A-H]MUX used as static src

- src/com/xilinx/rapidwright/edif/EDIFTokenizer.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFParser.java
Correct fix for https://github.com/Xilinx/RapidWright/pull/961, where the previous inability to account for the size of Unicode characters caused the wrong offsets to be calculated and the wrong part of the buffer to be read/written to.
> [EDIFTokenizer] Account for byte size of UTF-8 characters correctly

- src/com/xilinx/rapidwright/examples/SLRCrosserGenerator.java
- test/src/com/xilinx/rapidwright/examples/TestSLRCrosserGenerator.java
This updates the `SLRCrosserGenerator` tool to be able to independently update bus widths of signals traveling North and South.  Previously, the tool required the bus widths to be equal in width in both directions.  The relevant options are now:
`-w` : Sets the bus width for both North and South
`-j`: Sets the bus width for the North bound signals
`-k`: Sets the bus width for the South bound signals
`-w` cannot be used at the same time as `-j` or `-k`.  Also, using `-j` or `-k` requires the other so that both directions are unambiguously specified.  Error checking has been to ensure these requirements are met.  It also checks to ensure that the bus widths do not exceed a total of 1440 bits for each `LAGUNA` column.
> [SLRCrosserGenerator] Adds North/South parameterizable bus widths; some error checking

- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistReader.java
For nets with multiple source pins (e.g. `A_O` and `AMUX`) set the logical driver flag on the first PIP leaving the primary source.
> [RWRoute,PhysNetlistReader] Set logical driver on PIPs

- src/com/xilinx/rapidwright/design/DesignTools.java
When preparing a design to create a black box and ensure that the routing of the surrounding logic remains intact, sometimes the tool will attempt to insert a LUT1 as a way to preserve existing routing.  #967 stumbled on a bug where the tool found a scenario that fit the criteria for inserting a LUT1, but was not actually necessary as the source of the FF routing was actually internal to the SLICE (a GND post available for only `AFF` and `AFF2` as shown in this picture:
> [DesignTools.makeBlackBox()] Fix for #967

- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
When generating the Device Resources file for a Versal device, there is an NPE due to queries on the `DSP58` BELs `SRCMXINV` and `SRCFPMXINV` that don't match previous categorization of inverting capable BELs.  These BELs have multiple inverting pins and thus it is ambiguous which pins to return when `BEL.getNonInvertingPin()` and `BEL.getInvertingPin()` are called.
> Work around for multi-inverter BEL in DSP58

- test/shared/com/xilinx/rapidwright/util/VivadoToolsHelper.java
- test/src/com/xilinx/rapidwright/design/TestDCPSave.java
- test/src/com/xilinx/rapidwright/design/tools/TestLUTTools.java
- test/src/com/xilinx/rapidwright/eco/TestECOTools.java
- test/src/com/xilinx/rapidwright/examples/TestSLRCrosserGenerator.java
- test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
- test/src/com/xilinx/rapidwright/router/TestSATRouter.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
An upcoming release will support the ability to write out the EDIF netlist prior to detaching, without compromising the ability to write out a DCP checkpoint:
```
EDIFTools.writeEDIFFile(design.getNetlist(), <EDIF path>, ...);
design.detachNetlist();
design.writeCheckpoint(<DCP path>, <EDIF path>, ...);
```
> [DCP] Test Design.writeCheckpoint() when using existing EDIF

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
Rather than just consider nets used by `indirectConnections`, which would miss `directConnections` as well as any (exclusively) intra-site nets
> [RWRoute] Consider all nets for timing-driven routing

- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
The DCP writer depends on nets with a logical driver flag (used only for nets that use multiple site output pins for the same logical routing tree) to be the first source `PIP` in the list of pips on the `Net`.  These changes modify the addition of this flag in RWRoute such that it adheres to this convention.
> [RWRoute] Fix logical driver flag setting for DCP write

- src/com/xilinx/rapidwright/examples/PolynomialGenerator.java
- test/src/com/xilinx/rapidwright/design/TestDCPSave.java
* `PolynomialGenerator` to release `operators` cache after it's done, freeing up memory
* `TestDCPSave.testWriteCheckpointPreWrittenEDIF()` to check the written-out DCP file, rather than trying to write out the `Design` again.
> Fix PolynomialGenerator and TestDCPSave tests

- src/com/xilinx/rapidwright/placer/blockplacer/BlockPlacer2.java
I have identified an off by one error in the `BlockPlacer2` when we try to select a module instance to move: The upper bound for `Random.nextInt` is exclusive, but we subtract 1 anyway. Therefore we never select the very last module instance in the list of module instances. It will just stay at its initial placement position forever (unless it gets pushed away by overlapping with another instance).
This issue seems to have been there since the very beginning of RapidWright: https://github.com/Xilinx/RapidWright/blob/17af8990400fd86b79bf5e3284d3ba746aa643bc/com/xilinx/rapidwright/placer/blockplacer/BlockPlacer2.java#L401
@clavin-xlnx: This might explain some bad placement results we've seen in the past.
> BlockPlacer2: Fix off by one error in selecting module instance to move

- .classpath
- .github/workflows/build.yml
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/util/ParallelismTools.java
- src/com/xilinx/rapidwright/util/Params.java
Adds a new option (`Params.RW_WRITE_DCP_2024_1`) to write out DCPs in the 2024.1 format for faster reading by Vivado.
> Updates to support 2024.1 DCP writing

- src/com/xilinx/rapidwright/design/shapes/Shape.java
- src/com/xilinx/rapidwright/design/shapes/ShapeTools.java
- src/com/xilinx/rapidwright/interchange/LogNetlistReader.java
- src/com/xilinx/rapidwright/interchange/LogNetlistWriter.java
- src/com/xilinx/rapidwright/interchange/LogicalNetlist.java
This PR does the following
- Adds tags to the shapes (updates the schema to include them) 
- Maintains the order of the cells in the shapes relative to the shape file
- Also fixes a few issues: (1) the site types were not populated, now they are, (2) previously, if a run had generated the shapes file from Vivado there was an error, this now fixes that scenario.
> Shapes v2, adds tags, fixes issues

- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
Fixes three main issues with verifying an XCVP1902 device when exporting via the FPGA Interchange Format:
1. Fixes redundant reading in loops of site pins during verification that led to a Cap'n Proto "Read limit exceeded" message.
2. Removes the unused macros in the reference library in the same manner as when they are removed to be written out.  This was causing a mismatch previously.
3. Skips constant verification if the routing information is not present.
> [Interchange] Device Resources Verifier Fixes

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
For some macros, during expansion, some of their children are present in the netlist but don't have the proper pointer back to the main netlist object.  This ensure that the copy of the cell has the correct pointers.
> Fix null netlist pointer on expanded macro children

- src/com/xilinx/rapidwright/design/DesignTools.java
In #1009, a bad loop was added in an attempt to remove cells that appeared to be in encrypted cells that were part of the black box.  This loop has a flaw in it in that any cells with similar names, but not in the black box can be removed accidentally.  This causes a failure on an internal test and so it is best removed for now.
> [DesignTools.makeBlackBox()] Remove flawed loop intended for encrypted cell removal

- src/com/xilinx/rapidwright/util/DataVersions.java
Vivado 2024.1 has dropped support for the U280 devices and thus, their device model was missing in the RapidWright 2024.1.0 release.  This adds the device model back to allow users time to migrate to another platform as 2024.1 and later versions of Vivado won't support this device.
> Adding legacy support for u280

- src/com/xilinx/rapidwright/edif/EDIFTools.java
Write `*_load.tcl` into same dir as DCP rather than into current working dir
> [EDIFTools] writeTclLoadScriptForPartialEncryptedDesigns abspath

- test/src/com/xilinx/rapidwright/device/TestPIP.java
wire0,wire1 for a bidir PIP is unaffected, but wire1,wire0 will be changed to wire0,wire1 with reversed flag set
> [TestPIP] Test PIP constructor for reversed wires

- src/com/xilinx/rapidwright/rwroute/Connection.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraphTimingDriven.java
- src/com/xilinx/rapidwright/rwroute/TimingAndWirelengthReport.java
- src/com/xilinx/rapidwright/util/RuntimeTracker.java
- Fold `RouteNodeImpl` into `RouteNode` which is now a non-abstract *static* class -- static should remove one reference (to the outer `RouteNodeGraph`) from all `RouteNode` objects -- achieved by making necessary methods require a `RouteNodeGraph` reference instead of relying on that outer reference.
- Convert a number of counters (`RWRoute.{connectionsRouted{,Iteration}`, `RouteNodeGraph.nodesMapSize`, etc.) to `AtomicInteger` or `AtomicLong` to facilitate multi-threaded use
- Create `RWRoute.getQueue()` for getting the `PriorityQueue` to allow downstream (multi-threaded) classes to override
- Create a `ConnectionState` class to encapsulate all state necessary only when routing a particular connection
- General tidying up
> [RWRoute] Refactoring/cleanup/preparation for multi-threading

- .classpath
- .github/workflows/build.yml
- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/edif/EDIFCell.java
- src/com/xilinx/rapidwright/edif/EDIFLibrary.java
- src/com/xilinx/rapidwright/edif/EDIFLibraryBuiltin.java
- src/com/xilinx/rapidwright/edif/EDIFLibraryNoNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/examples/PolynomialGenerator.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
- src/com/xilinx/rapidwright/interchange/EnumerateCellBelMapping.java
- test/src/com/xilinx/rapidwright/device/TestUnisimPlacements.java
* `EDIFCell.setLibrary()` can no longer be used to move an `EDIFCell` to another library. This prevents the builtin "singleton" cell maintained by RapidWright from being moved out of the singleton library into a user library. Purposely moving `EDIFCell`-s now requires a `EDIFLibrary.removeCell()` first.  
This prevention is necessary to ensure that such cells can't be attached to a user design, which then prevents the user netlist from being GC-ed.
* `EDIFLibrary.setNetlist()` is modified in the same way as for `EDIFCell.setLibrary()`.
* `EDIFLibrary.addCell()` will now make a shallow copy of an `EDIFCell` if it already belongs to a library.
* Updates required to support the above changes
* Migrate to new API `Cell.getCompatiblePlacements(Device)`
>  EDIF cleanup preventing singleton cells/libraries from attaching to user designs

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/interchange/LogicalNetlistToEdif.java
As Vivado must work with macros for the logical netlist, the default behavior of `LogicalNetlistToEdif`, which expands all macros, leads to an `opt_design` error in implementation of the post-synthesis project built on the output EDIF file. This error is evident in the following output:
> Command: opt_design
> Attempting to get a license for feature 'Implementation' and/or device 'xcvp1002'
> INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xcvp1002'
> Running DRC as a precondition to command opt_design
> 
> Starting DRC Task
> INFO: [DRC 23-27] Running DRC with 8 threads
> ERROR: [DRC INBB-3] Black Box Instances: Cell 'ibufds/DIFFINBUF_INST' of type 'DIFFINBUF' has undefined contents and is considered a black box.  The contents of this cell must be defined …
> Make LogicalNetlistToEdif not expand macros by default

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
In `RouterHelper.routeDirectConnection(Connection directConnection)`, the field `nodes` of `directConnection` will be assigned a `null` value when `RouterHelper.findPathBetweenNodes` fails to find a path for it. This leads to `NullPointerException`s in `RWRoute.{postRouteProcess, computesNodeUsageAndTotalWirelength}`, and prevent the router from completing the output process. It would be more reasonable to allow the process to finish even if it fails to route some direct connections, as this would provide better debugging capabilities.
> [RWRoute] Assign empty list when direct connections fails

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/design/merge/MergeDesigns.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFTools.java
- src/com/xilinx/rapidwright/util/VivadoTools.java
Resets the parent net map after each merge to avoid stale references.  Also refactors how encrypted cells are loaded in the `_load.tcl` script (however, has no significant affect on runtime).
> Fix for design merging, including designs with encrypted cells

- src/com/xilinx/rapidwright/design/DesignTools.java
as part of the `DesignTools.createCeSrRstPinsToVCC()` method which gets called by `RWRoute.preprocess()`
> [DesignTools] Conform to Vivado *RST* pin inversion site routing configuration 

- src/com/xilinx/rapidwright/interchange/DeviceResourcesVerifier.java
- src/com/xilinx/rapidwright/interchange/DeviceResourcesWriter.java
This PR changes the export order of tiles ([`tileList`](https://github.com/chipsalliance/fpga-interchange-schema/blob/c985b4648e66414b250261c1ba4cbe45a2971b1c/interchange/DeviceResources.capnp#L102)) and tile types ([`tileTypeList`](https://github.com/chipsalliance/fpga-interchange-schema/blob/c985b4648e66414b250261c1ba4cbe45a2971b1c/interchange/DeviceResources.capnp#L101)) in Interchange `.device` files such that the order reflects the original Vivado-given index.  
**Tiles:** Each tile in a device is given a unique address or `INDEX` that is often computed by `TOTAL_DEVICE_COLUMNS*TILE_ROW + TILE_COLUMN`.  This PR now orders the tiles in the device resources file according to this index.
**Tile Types:** The Interchange has a Tile Type object, but Vivado annotates tile type information …
> [Interchange] Reorders tile types and tiles to follow their Vivado index

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/design/tools/RelocationTools.java
- test/src/com/xilinx/rapidwright/design/TestRelocationTools.java
Creating a command line accessible way to perform a raw relocation of the implementation inside a DCP.  This adds two usage modes to `RelocationTools`: 
```
USAGE (query valid relocation options): <input.dcp>
USAGE (to relocate a design): <input.dcp> <output.dcp> <tile_x_offset> <tile_y_offset>
```
> Creating a standalone entry point to relocate DCPs

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/rwroute/CUFR.java
- src/com/xilinx/rapidwright/rwroute/CUFRpartitionTree.java
- src/com/xilinx/rapidwright/rwroute/PartialCUFR.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
This is a re-created PR of https://github.com/Xilinx/RapidWright/pull/1049. Related information can be seen in:
- https://github.com/Xilinx/RapidWright/pull/1049#issuecomment-2289321816
- https://github.com/Xilinx/RapidWright/pull/1049#issuecomment-2289743432
> Add recursive partitioning ternary tree (RPTT)

- .github/workflows/build.yml
Since @v2 is now deprecated and causes a failure.
Builds on commit from #1057.
> [GitHub Actions] Migrate to upload-artifact@v4

- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
Now produces a Vivado-clean result.
> Fix testRouteStaticNet() to avoid site pins, and fix golden values

- .github/workflows/build.yml
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
Very rare behaviour described below.
Context: Net1 is a fully routed net utilizing a number of nodes (Node1, Node2, Node3, ...)
1. During clock routing, it's decided that Node1 is needed to complete the clock net, and so the entirety of Net1 is unpreserved, and the result of the clock route is then preserved.
2. During static net routing, Node2 is determined to be needed to complete a static net. Since Node2 is no longer being preserved, the static net gets to preserve it. 
Note that because Node2 was unpreserved previously, it already exists in the routing graph as a `RouteNode`. 
3. Later, during signal routing, this node breaks the assumption that preserved nodes can only be used by the same net pointed to by its `prev` pointer.
This PR allows clears this `prev` pointer so that this …
> [RWRoute] Always clear prev pointer of unpreserved RouteNode-s

- src/com/xilinx/rapidwright/edif/EDIFPort.java
- src/com/xilinx/rapidwright/edif/EDIFPortInst.java
- src/com/xilinx/rapidwright/edif/EDIFWriteLegalNameCache.java
- src/com/xilinx/rapidwright/examples/MultGenerator.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
There are two competing issues relevant to this fix.
1. There are unfortunately situations where an `EDIFCell` can have two `EDIFPort` objects, a single bit port and a bussed port with the same name, for example `my_signal` and `my_signal[1:0]`.  We resolve this naming collision by storing the bussed version with a `[` suffix, `my_signal[`.  
2. In some designs, it is possible to have two `EDIFPort` objects belonging to the same `EDIFCell` such that when one bussed name is EDIF legalized, it collides with another valid `EDIFPort` name.  For example, `phy_ctrl[1:0]` and `phy_ctrl_[13:0]`.  Due to the possible naming collision issues from issue 1, all bussed ports are given a `[` suffix to the name and thus the legal names of busses are all extended by one character, `phy_ctrl`  (original) …
> [EDIF] Fixes rare bus renaming collision

- test/src/com/xilinx/rapidwright/device/TestBEL.java
`DIFFRXTX` on Versal returns true for `BEL.isFF()` which doesn't seem correct.
`DIFFINBUF` and `DIFFOUTBUF` on US+ also returns true.
> [TestBEL] Add testDIFFsAreNotFF()

- test/src/com/xilinx/rapidwright/design/TestDesign.java
- test/src/com/xilinx/rapidwright/design/TestNet.java
Looks like the net order of DCPs generated by Vivado >=2022.1 could be read non-deterministically. DCPs generated by RapidWright are unaffected. This test aims to demonstrate this issue (but perhaps unable to do so with GitHub Actions' free runners).
> [TestDesign] Add test for net ordering of >= 2022.1 DCPs

- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
Mostly reverting https://github.com/Xilinx/RapidWright/pull/759.
Also fix an issue with same LUT source being used illegally to serve VCC and GND.
> [PartialRouter] Disable ripup in global/static routing

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
Fix incorrect assumption about VCC routing on UltraScale inadvertently added in https://github.com/Xilinx/RapidWright/pull/1059.
```
// On UltraScale, certain site pins (e.g. SLICE/CKEN_B1[1-4], SLICE/SRST_B[12])
// do not have an uphill PIP to VCC_WIRE (instead they have one to GND_WIRE, which
// Vivado itself chooses not to use)
```
> [GlobalSignalRouting] Fix VCC routing for UltraScale

- src/com/xilinx/rapidwright/interchange/PhysNetlistReader.java
Necessary since https://github.com/Xilinx/RapidWright/pull/1040 requires `SiteInst.getDesign()`
> [PhysNetlistReader] Call SiteInst.setDesign() even for STATIC_SOURCEs

- src/com/xilinx/rapidwright/rwroute/Connection.java
- src/com/xilinx/rapidwright/rwroute/NetWrapper.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- src/com/xilinx/rapidwright/util/VivadoTools.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
- `RWRoute` to not check for sink routability anymore
- `PartialRouter` to only check sink routability after all nodes have been preserved
- `RWRoute.handleUnroutableConnection()` to abandon connections that are guaranteed to be unroutable since the bounding box is never enlarged (nor any nets be unpreserved, in the case of `PartialRouter`)
- `RWRoute` to not pre-emptively set up the second source; do so only when needed in `RWRoute.swapOutputPin()` or when recovering partially routed nets in `PartialRouter`
- Various cleanups/optimizations
> [RWRoute] Further cleanup

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
To ensure pins are generated if not done already
> [EDIFNetlist] getPhysicalPins() to call getPhysical{Gnd,Vcc}Pins()

- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- src/com/xilinx/rapidwright/util/Utils.java
Without which this method (which uses breadth-first search) could take a while.
Also added `Utils.isClocking()` method to detect clocking tiles.
Only two entries so far, from Versal, affecting a failing testcase. Will add more as and when needed.
> [RouterHelper] findPathBetweenNodes() to ignore clocking tiles

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- src/com/xilinx/rapidwright/rwroute/TimingAndWirelengthReport.java
... instead of list which was never used anyway.
This brings it in line with `projectOutputPinToINTNode()` which returns a single node too.
> [RouterHelper] projectInputPinToINTNode() to return solitary node

- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- src/com/xilinx/rapidwright/util/Utils.java
- test/src/com/xilinx/rapidwright/rwroute/TestRouterHelper.java
Much like `projectInputPinToINTNode()` as this seems necessary for Versal I/Os (and even fixed #558!)
Without this, in an upcoming `PartialRouter` test with `picoblaze_2022.2.dcp`, the projected result is not the same as Vivado's solution thereby leading to an unroutable situation.
> [RouterHelper] projectOutputPinToINTNode() to breadth-first-search

- src/com/xilinx/rapidwright/util/FileTools.java
- `FileTools.runCommand(String[] command, ...)` is an array overload of `FileTools.runCommand(String command, ...)` for arguments with spaces in
- `FileTools.getExecutablePath(String)` is the generalized guts of `FileTools.getVivadoPath()`
> [FileTools] Add runCommand(String[] ...) & getExecutablePath(String)

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/util/ReportRouteStatus.java
- src/com/xilinx/rapidwright/util/ReportRouteStatusResult.java
- test/src/com/xilinx/rapidwright/util/TestReportRouteStatus.java
Quite rudimentary check for partially/fully unrouted nets, as well as conflicts.
> Add ReportRouteStatus utility

- src/com/xilinx/rapidwright/edif/EDIFWriteLegalNameCache.java
Fixes `ConcurrentModificationException`
> [EDIFWriteLegalNameCache] busCollisionRenames to be a ConcurrentHashMap

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/design/NetTools.java
- test/src/com/xilinx/rapidwright/design/TestNetTools.java
```
/** Compute the node routing tree of the given Net by examining its PIPs.
* Note that this method: (a) assumes that no loops are present, (b) only discovers subtrees that start at an
* output SitePinInst or a node tied to VCC/GND (i.e. gaps and islands will be ignored).
```
The `NodeTree` class extends the existing `Node` class by adding a new `fanouts` field.
`NodeTree.toString()` emulates Vivado's `report_route_status -of [get_nets ...]` output.
`DesignTools.updatePinsIsRouted()` now leverages this method.
> [NetTools] Add getNodeTrees() method and NodeTree class

- src/com/xilinx/rapidwright/design/tools/LUTTools.java
- test/src/com/xilinx/rapidwright/design/tools/TestLUTTools.java
Vivado expects a zero-padded INIT string associated with LUTs, this PR ensures the INIT strings derived from equations are properly zero-padded.
> [LUTTools] Add zero padding to LUT INIT strings

- .github/workflows/build.yml
- common.gradle
- Updating a number of actions to eliminates warnings.
- Remove `gradle/wrapper-validation-action` which just checks Gradle Jar integrity
- GitHub-hosted runners now have 16G RAM.
> Update actions and do not limit to 5G RAM

- src/com/xilinx/rapidwright/rwroute/Connection.java
- src/com/xilinx/rapidwright/rwroute/NetWrapper.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeInfo.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeType.java
- src/com/xilinx/rapidwright/rwroute/TimingAndWirelengthReport.java
- test/src/com/xilinx/rapidwright/device/TestNode.java
* `RouteNodeType.NON_LOCAL` are the single, double, quad, long wires that travel between INT tiles, along with the uphill muxes (e.g. `INT_NODE_SDQ_*`) that feed them.
* `RouteNodeType.LOCAL` is everything else (e.g. `INT_NODE_IMUX_*`) that is used to connect `NON_LOCAL` to sinks.
This PR optimizes the rather messy https://github.com/Xilinx/RapidWright/pull/893 that kept a set of wire indices that were allowed to be used. Now, `RouteNode.type` indicates whether a node is local or non-local, with the idea that you should only leave your non-local node onto a local one if you are in the vicinity of the sink, since once you are a local node you cannot use a non-local node again (unless LUT routethrus are considered).
Furthermore:
* `RouteNodeType.PINFEED_O` is now `EXCLUSIVE_SOURCE`
* …
> [RWRoute] Divide nodes into LOCAL and NON_LOCAL

- src/com/xilinx/rapidwright/design/blocks/PBlock.java
- src/com/xilinx/rapidwright/design/tools/Edge.java
- src/com/xilinx/rapidwright/design/tools/TileGroup.java
- src/com/xilinx/rapidwright/device/browser/DeviceBrowser.java
- src/com/xilinx/rapidwright/device/browser/DeviceBrowserScene.java
- src/com/xilinx/rapidwright/device/browser/ThreadedDeviceBrowser.java
- src/com/xilinx/rapidwright/gui/NumberedHighlightedTile.java
- test/src/com/xilinx/rapidwright/design/tools/TestTileGroup.java
Adds a `TileGroup` object that is a contiguous rectangular range of tiles that can be highlighted in the `DeviceBrowser` or used for various tasks.
Updates the DeviceBrowser with a few new features:
1. Adds a Nodes sidebar that lists the `Node` objects present in a `Tile` and also allows infinite tree expansion based on uphill and downhill connectivity:
2. Enables a threaded `DeviceBrowser` instance (see `DeviceBrowser.getWindow()`) that can live in an interpreter environment making interaction possible.  This is useful for Python/Jython/Jshell instances.
3. Adds functionality to highlight/unhighlight `TileGroup` edge tiles:
> TileGroup and DeviceBrowser Improvements

- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- src/com/xilinx/rapidwright/util/Utils.java
- test/src/com/xilinx/rapidwright/rwroute/TestRouterHelper.java
Without which `RouterHelper.projectOutputPinToINTNode()` will have its watchdog expire and cause a routing failure for the `boom_med_pb` benchmark from the [FPGA24 Routing Contest](https://github.com/Xilinx/fpga24_routing_contest)
Also `RouterHelper.projectInputPinToINTNode()` failed too which required a bit more fixing.
> [Utils] isClocking() to include TileTypeEnum.CMT_L

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
Checking that all such pins are available (and removing those that are not available, such as those occurring in encrypted designs where it's not possible to infer all pins on signal nets)
To achieve this, `addStaticNetRoutingTargets()` now preserves static nets' PIPs and *output* pins only; preservation of input pins is deferred to `routeStaticNets()` (at which point all signal nets' routing will have been preserved) --- which can move or remove input pins between/from static nets --- before doing so.
Also remove a GlobalSignalRouting optimization added in https://github.com/Xilinx/RapidWright/pull/1059 for static nets that encourages reuse -- that optimization didn't kick in anyway, since static sinks were not always preserved, to ensure tests continue to pass.
> [GlobalSignalRouting] routeStaticNets() to take a list of static pins

- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
Sinks in Laguna tiles must be Laguna registers (but will be projected into the INT tile) however, it's possible for another net to sneak in and use that sink node as a bounce -- this PR prevents that.
> [RWRoute] Preserve nodes of Laguna sinks

- src/com/xilinx/rapidwright/rwroute/CUFR.java
- src/com/xilinx/rapidwright/rwroute/PartialCUFR.java
Since it's the default for CUFR. Emit warning if not enabled.
> [CUFR] CUFR and PartialCUFR to default to --hus

- src/com/xilinx/rapidwright/design/ModuleInst.java
`ModuleInst.place()` has a flag to request that no overlapping modules should be allowed.  There was a bug where this was not behaving as expected.  This attempts to align the behavior with the intent of the method.
> [ModuleInst] Fix placement behavior when requesting no overlaps

- src/com/xilinx/rapidwright/design/NetTools.java
- src/com/xilinx/rapidwright/design/tools/RelocationTools.java
This avoid looking for gap routing as a proxy check to see if a net is a clock.
> [NetTools] Add check for net driving clock sinks

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/rwroute/GlobalSignalRouting.java
- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
1. Tie off `MMCM.CLKFBIN` and `MMCM.CLKIN2` site pins to VCC if unused.
2. `RouterHelper.invertPossibleGndPinsToVccPins()`: Unroute intra-site net when inverting (and do not reroute)
When inverting `SitePinInst`s from being on the GND net to the VCC net, unpaint the sitewire if there's an inverter.
> RWRoute preprocessing fixes

- src/com/xilinx/rapidwright/rwroute/CUFR.java
- src/com/xilinx/rapidwright/rwroute/PartialCUFR.java
- src/com/xilinx/rapidwright/rwroute/PartialRouter.java
- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RapidStreamRoute.java
In particular, calling `CUFR.main()` and `PartialCUFR.main()` (as you would do when invoking from the command line) should have [HUS](https://github.com/Xilinx/RapidWright/pull/1043) enabled by default.
Plus some smaller cleanups.
> [RWRoute] Small cleanup; enable CUFR by default

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/eco/TestECOTools.java
- test/src/com/xilinx/rapidwright/interchange/TestPhysNetlistWriter.java
- test/src/com/xilinx/rapidwright/rwroute/TestGlobalSignalRouting.java
Previously returned `void`. 
Helpful for determining if anything needs to be routed.
> [DesignTools] updatePinsIsRouted() to return num unrouted sinks

- src/com/xilinx/rapidwright/design/tools/LUTTools.java
- test/src/com/xilinx/rapidwright/design/tools/TestLUTTools.java
* Alternate way to extract site pin name despite presence of Versal IMRs
* Update intra-site routing when pin swapping (necessary for Versal due to those IMRs)
> [LUTTools] Versal pin swapping fixes

- .classpath
- .github/workflows/build.yml
- src/com/xilinx/rapidwright/util/Params.java
- src/com/xilinx/rapidwright/util/VivadoTools.java
- test/src/com/xilinx/rapidwright/design/TestDCPWrite.java
Allows users to disable any Advanced Flow flags when writing out DCPs  by setting the param `RW_DISABLE_WRITING_ADV_FLOW_DCPS`.
> Adds an Override Flag for Advanced Flow Settings in Designs

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/router/RoutingHeatMap.java
A simple example application that reads in a DCP and outputs a CSV of the routing used in each INT tile of the design.  This can be imported into Excel and using the conditional coloring option by selecting all of the non-empty cells:
This can then generate a heat map of routing congestion:
To run this example from scratch:
```
git clone -b routing_heat_map --recursive https://github.com/Xilinx/RapidWright.git
cd RapidWright
./gradlew compileJava
bin/rapidwright RoutingHeatMap test/RapidWrightDCP/picoblaze_2022.2.dcp picoblaze_2022.2.csv
```
Then you can open the csv in Excel or a similar tool.
> Routing Heat Map Example

- src/com/xilinx/rapidwright/design/DesignTools.java
In large removals involving MakeBlackBox, the partial removal of some nets becomes extremely slow due to the nature of how individual pins are unrouted.  This update will batch pin removals to enable a dramatically better runtime performance (several hours down to 5 minutes in one case).
> [DesignTools] Fix scaling issue with MakeBlackBox

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/ipi/BlockStitcher.java
This is a few fixes/work arounds to enable the `BlockStitcher` to run on 2024.2 designs from Vivado.  
1. Consolidate the final netlist set of cells to the `work` library and update all references of the work library to the canonical instance in the netlist.
2. Change the name of the design to match the incoming netlist top cell name.
3. Works around a reference issue for pass-thru port connections where the `EDIFPortInst` has a null reference to its `EDIFCellInst`.  It works around this issue by referencing the `EDIFCellInst` in the `EDIFHierCellInst` instead.
4. The BlockStitcher relies on operating on a null netlist, however, modern changes do not allow this.  A work around is added that puts a temporary 'dummy' netlist in place and then removes it.
See also #1124.
> [BlockStitcher] Work arounds to address stitching issues in latest Vivado 2024.2

- src/com/xilinx/rapidwright/design/RTLStubGenerator.java
- src/com/xilinx/rapidwright/edif/EDIFPort.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFPort.java
If a single-bit bus was declared, it was not being exported properly by the EDIF writer.  This attempts to fix this issue.
> [EDIF] Fix Export of Single Bit Busses

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
When unrouting cell pins, the clock pins `CLKARDCLK` and `CLKBWRCLK` often fanout to two BEL pins  `CLKARDCLK=[CLKARDCLKU, CLKARDCLKL]`, for example.  This change ensures that both pins are unrouted when requested in `DesignTools.unrouteCellPinSiteRouting()`
> [DesignTools] Unroutes both CLK pins on a BRAM when requested

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
This is a less common case that can occur around a CARRY's inputs.  Previously, the method was mistaking the fact that a LUT output was simply driving an input pin on the CARRY that led to it being unrouted, but in reality, they are not connected.
> [DesignTools] Ensure cell pin has a logical connection before attempting to unroute it

- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- test/src/com/xilinx/rapidwright/edif/TestEDIFNetlist.java
Adds a flag to `EDIFNetlist.copyCellAndSubCells()` and variants to uniquify cells upon name collision instead of error out.
> [EDIFNetlist] Add flag to uniquify copied cells 

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/eco/TestECOTools.java
Discovered an issue when removing A6LUT cell (LUT1) before CARRY8 cell caused the site routing to be left in undesirable state to fully remove the routethru in H6LUT.  
This change checks to make sure when traversing other potential sinks that it only continues if the routethru cell encountered is servicing the currently explored cell's pin.
> [DesignTools] Fix routethru corner case in fullyUnplaceCellHelper()

- src/com/xilinx/rapidwright/design/DesignTools.java
Fixes a bug introduced in #1151.
> [DesignTools] Handle case when Cell.getAllPhysicalPinMappings() is null

- src/com/xilinx/rapidwright/util/CodeGenerator.java
- test/src/com/xilinx/rapidwright/util/TestCodeGenerator.java
This PR augments the `CodeGenerator` with a new method that can take an existing `SiteInst` and re-generate a new `Design` object with the same `SiteInst` configuration with the following modifications:
- The names of cells and nets are changed such that they are simple enumerations (`net0`, `net1`, `cell2`, ...).  This allows users to generate a test of a single `SiteInst` without sharing any information related to the existing design
- All site routing, routethrus, sitePIPs, and cells in the site are preserved and reproduced.  Any nets that connect to the `SiteInst` are re-created, but are only ported up to the top level.  Multiple site instances are currently not supported.
For example, the provided test will generate the following configured `SiteInst`:
> [CodeGenerator] Creates Java Code to Construct a Test Design With a Single Example SiteInst 

- src/com/xilinx/rapidwright/MainEntrypoint.java
- src/com/xilinx/rapidwright/examples/CountRoutedNets.java
This simple tool discussed in [#1152] & [#1161] to help user get the partial routed net (site pin conflict) to further debug with the route fail case from Vivado.
The # of nets reported in RapidWright is the same as the tcl command ```report_route_status``` in Vivado.
1. Fully placed & route design:
The number match in the Vivado report_route_status # of routable nets
2. Route fail design:
The code snippet in GetRouteNets.java will get the number of site pin conflict as report in # of nets with unrouted pins in Vivado report_route_status command and also show the detail info about the net and the pins.
Thanks
> Get Partial Routed Net Examples

- .github/workflows/test-rapidwright-wrapper.yml
Same as for the `build` workflow, otherwise we were getting:
```
Error: Cache service responded with 422
```
failures.
> [Actions] Update test-rapidwright-wrapper to setup-java@v4

- src/com/xilinx/rapidwright/design/DesignTools.java
This is useful when populating an abstract shell that contains partition pin routes that need to be preserved.
> [DesignTools] Adds option to preserve routing on populateBlackBox()

- src/com/xilinx/rapidwright/design/NetTools.java
First found in the Kria KR260.
> [NetTools] Recognize BUFGCE_HDIO as a clock src site

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/design/NetTools.java
To accept VCC sitewires when searching for GND sitewires, since the latter will invert to the former
> [DesignTools] getAllRoutedSitePinsFromPhysicalPin() fix

- src/com/xilinx/rapidwright/design/DesignTools.java
- src/com/xilinx/rapidwright/design/NetTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
- test/src/com/xilinx/rapidwright/design/TestNetTools.java
Also fixing the `NetTools.getNodeTrees()` that it depends on, by identifying nodes that are multiply-driven so that consumers (e.g. `updatePinIsRouted()`) will not repeatedly descend down routing loops.
Fixes #1183.
> [DesignTools] updatePinIsRouted() to handle routing loops

- src/com/xilinx/rapidwright/edif/EDIFTools.java
Rather than `EDIFHierCellInst` objects since they can be invalidated when something in its hierarchy is uniquified first.
> [EDIFTools] uniqueifyNetlist() to use hier paths to cells

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
When converting cells to black boxes in unplaced designs (`Cell` objects are present, but they are not placed), a few NPEs cropped up and also found some redundant/simplifications.
> [MakeBlackBox] Fixes for unplaced designs

- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- test/shared/com/xilinx/rapidwright/support/rwroute/RouterHelperSupport.java
- test/src/com/xilinx/rapidwright/rwroute/TestRouterHelper.java
Where #910 inverted the physical connection of LUT input pins, the logical connection was not inverted.
Now fixed in this PR, with an updated test.
> [RouterHelper] Invert logical connection of LUT input pins

- src/com/xilinx/rapidwright/rwroute/Connection.java
A problem surfaces when LUT pin swapping is enabled for RWRoute. Under this feature, LUT sinks are no longer exclusive (and marked as being used) to the associated net and so the condition `sinkRnode.countConnectionsOfUser(netWrapper) == 1` will not be true; the primary sink will not be marked as being a viable target, however only the alternate sinks will be marked.
In the rare situation (as seen for the FPGA24 routing contest's `finn_radioml` benchmark) where the primary sink is the only sink that is reachable, this leads to an unroutable situation.
The comment in the removed code appears to be stale and the outer `if` condition was modified as part of #1107: https://github.com/Xilinx/RapidWright/commit/4f38f60537e0c6d63c0beecd7ba899113b703e80#diff-c35f040a5ca8f8a23765deeb2575531451fec53 …
> [RWRoute] Connection.setAllTargets() to always set primary sink

- src/com/xilinx/rapidwright/eco/ECOTools.java
`CARRY8.CIN` can be logically connected to `VCC`, but does not physically need routing since it can be sourced from inside the BEL.
Do not error out in such cases.
> [ECOTools] Fix connectNet() for pins that don't need routing

- .classpath
- .github/workflows/build.yml
- src/com/xilinx/rapidwright/design/tools/InlineFlopTools.java
- src/com/xilinx/rapidwright/eco/ECOPlacementHelper.java
- src/com/xilinx/rapidwright/edif/EDIFNet.java
- src/com/xilinx/rapidwright/edif/EDIFNetlist.java
- src/com/xilinx/rapidwright/edif/EDIFPort.java
- src/com/xilinx/rapidwright/util/StringTools.java
- src/com/xilinx/rapidwright/util/VivadoTools.java
- test/shared/com/xilinx/rapidwright/util/VivadoToolsHelper.java
- test/src/com/xilinx/rapidwright/design/TestCell.java
A tool designed to attached (and remove in a separate invocation) inline flip-flops to ports of an out-of-context DCP.  This is to help routability for kernels once put in-context that will be replicated later.
> Inline Flop Insertion/Removal Tool 

- src/com/xilinx/rapidwright/util/DataVersions.java
An issue was found where the unisim primitive mappings for the Versal architecture were out of sync with the released device models.  This PR updates the unisim mappings to bring them up to date with the 2025.1 release.  This was found via #1259.
> Update Versal Unisims

- src/com/xilinx/rapidwright/rwroute/RWRoute.java
- src/com/xilinx/rapidwright/rwroute/RouteNode.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeGraph.java
- src/com/xilinx/rapidwright/rwroute/RouteNodeInfo.java
- src/com/xilinx/rapidwright/rwroute/RouterHelper.java
- test/src/com/xilinx/rapidwright/rwroute/TestRWRoute.java
Certain devices (e.g. vp1202) use a `SLL` tile type instead of a `CLE_BC_CORE`. Add support for that here. 
Turns out that tile type is at the very least necessary to reach the `LAG_?` site pin, let alone using `BNODE`/`CNODE`s that don't live in `CLE_BC_CORE` tiles.
> [RWRoute] Add support for SLL tile types

- src/com/xilinx/rapidwright/examples/ReportTimingExample.java
- src/com/xilinx/rapidwright/timing/TimingGraph.java
- test/src/com/xilinx/rapidwright/timing/TestTimingGraph.java
This PR improves the [Report Timing Example](https://www.rapidwright.io/docs/ReportTimingExample.html) so that the path print out is more informative.  It also adds a view convenience methods for getting timing paths and calculating the total delay of the path.  Here are the main APIs added to `TimingGraph`:
- `public void prettyPrintPathDelays(GraphPath<TimingVertex, TimingEdge> path)`
- `public GraphPath<TimingVertex, TimingEdge> getTimingPath(String src, String snk)`
- `public GraphPath<TimingVertex, TimingEdge> getTimingPath(EDIFHierPortInst src, EDIFHierPortInst snk)`
- `public Float getPathDelay(GraphPath<TimingVertex, TimingEdge> path)`
**AFTER**
```
All Delays in picoseconds (ps):
Net | Logic | Physical Site/BEL Pins                          | Logical Pins …
```
> [TimingGraph] Improving Report Timing Example; add some APIs 

- src/com/xilinx/rapidwright/design/DesignTools.java
If the top level design is driving one of the ports of the black box with GND or VCC, this should recognize that it should switch the parent net to their physical net equivalents (`GLOBAL_LOGIC[1|0]`).
> [DesignTools] Handles VCC/GND connections properly in populateBlackBox()

- src/com/xilinx/rapidwright/design/DesignTools.java
- test/src/com/xilinx/rapidwright/design/TestDesignTools.java
`DesignTools.createCeClkOfRoutethruFFToVCC()` is responsible for examining the physical netlist to discover the presence of FFs configured as routethrus and ensuring that their `CE` pins are connected to VCC, and their `CLK` pins are connected to GND (which is supplied via inversion from VCC). This operation only applied to US/US+ but not to Versal, since Versal now has a mux to bypass the flop without needing routethru.
It turns out this same operation is also necessary for the `AND2B1L` and `OR2L` unisims (and perhaps more; these seem to be the only two officially supported ones according to [UG974 for US/US+](https://docs.amd.com/r/en-US/ug974-vivado-ultrascale-libraries) and [UG1344 for Versal](https://docs.amd.com/r/en-US/ug1344-versal-architecture-libraries))
Do we want to change …
> [DesignTools] createCeClkOfRoutethruFFToVCC() to handle AND2B1L/OR2L
